package kr.co.ta9.pandora3.pmbr.dao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;

/**
 * TmbrCluHstDao - DAO(Data Access Object) class for table [TMBR_CLU_HST].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TmbrCluHstDao extends BaseDao {
	/**
	 * 약관이력 조회 (그리드형)
	 * @param parameterMap
	 * @return JSONObject
	 * @throws Exception
	 */
	public JSONObject getTmbrCluHstList(ParameterMap parameterMap) throws Exception{
		return queryForGrid("TmbrCluHst.getTmbrCluHstList", parameterMap);
	}
}