package kr.co.ta9.pandora3.landing.dao;

import java.util.List;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.usrdef.BpcmCommPopVO;

/**
 * TbbsDocInfDao - DAO(Data Access Object) class for table [TBBS_DOC_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class BpcmCommPop001Dao extends BaseDao {
	
	/**
	 * 자점팝업 조회
	 * @param  parameterMap
	 * @return SysDocument
	 * @throws Exception
	 */
	public JSONObject selectCstrGridList(ParameterMap parameterMap) throws Exception { 
		return queryForGrid("BpcmCommPop001.selectCstrGridList", parameterMap);
	}
	
	/**
	 * user 자점 조회
	 * @param  parameterMap
	 * @return SysDocument
	 * @throws Exception
	 */
	public List<BpcmCommPopVO> selectUserCstrList(ParameterMap parameterMap) throws Exception { 
		return getSqlSession().selectList("BpcmCommPop001.selectUserCstrList", parameterMap);
	}
}