package kr.co.ta9.pandora3.landing.dao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;

/**
 * TbbsDocInfDao - DAO(Data Access Object) class for table [TBBS_DOC_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class Bpcm3001Dao extends BaseDao {
	
	/**
	 * 사은행사 목록 조회
	 * @param  parameterMap
	 * @return SysDocument
	 * @throws Exception
	 */
	public JSONObject selecThkuEvntList(ParameterMap parameterMap) throws Exception { 
		return queryForGrid("Bpcm3001.selectThkuEvtList", parameterMap);
	}
	
	/**
	 * 사은행사 목록 조회
	 * @param  parameterMap
	 * @return SysDocument
	 * @throws Exception
	 */
	public JSONObject selectThkuEvtDtl(ParameterMap parameterMap) throws Exception { 
		return queryForGrid("Bpcm3001.selectThkuEvtDtl", parameterMap);
	}
}