package kr.co.ta9.pandora3.landing.dao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.landing.dao.base.BaseLandingDao;

/**
 * TbbsDocInfDao - DAO(Data Access Object) class for table [TBBS_DOC_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class LandingDao extends BaseLandingDao {

	
	
	public JSONObject getWeather(ParameterMap parameterMap) throws Exception {
		return queryForGrid("Landing.getWeather", parameterMap);
	}
	
	
}