package kr.co.ta9.pandora3.landing.dao;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TbDmcmMktgrcmcgrpsmryF;

/**
 * TbbsDocInfDao - DAO(Data Access Object) class for table [TBBS_DOC_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TbDmcmMktgrcmcgrpsmryFDao extends BaseDao {
	
	
	/**
	 * mkt 조회
	 * @param  parameterMap
	 * @return SysDocument
	 * @throws Exception
	 */
	public TbDmcmMktgrcmcgrpsmryF getMktData(ParameterMap parameterMap) throws Exception { 
		return getSqlSession().selectOne("TbDmcmMktgrcmcgrpsmryF.getMktData", parameterMap);
	}
}