package kr.co.ta9.pandora3.landing.dao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TbVmcsLngeutlprcoS;

/**
 * TbbsDocInfDao - DAO(Data Access Object) class for table [TBBS_DOC_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TbVmcsLngeutlprcoSDao extends BaseDao {
	
	
	/**
	 * 라운지 조회
	 * @param  parameterMap
	 * @return SysDocument
	 * @throws Exception
	 */
	public JSONObject getLngeutlprco(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TbVmcsLngeutlprcoS.getLngeutlprco", parameterMap);
	}

	/**
	 * 라운지 상세 조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public TbVmcsLngeutlprcoS getDetailLngeutlprco(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectOne("TbVmcsLngeutlprcoS.getDetailLngeutlprco", parameterMap);
	}
}