package kr.co.ta9.pandora3.pcommon.dto;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbPdrCmpnyStafjobD;

/**
 * TbPdrCmpnyStafjobD - ValueObject Extended class for table [TB_PDR_CMPNY_STAFJOB_D].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 05. 21
 */
@Repository
public class TbPdrCmpnyStafjobD extends BaseTbPdrCmpnyStafjobD {

	private String crtr_id;
	private String content_cd;
	private String content_nm;
	private String content_rmk;
	private String search;
	private String cd;
	private String nm;
	
	public String getCrtr_id() {
		return crtr_id;
	}

	public void setCrtr_id(String crtr_id) {
		this.crtr_id = crtr_id;
	}

	String getContent_cd() {
		return content_cd;
	}

	void setContent_cd(String content_cd) {
		this.content_cd = content_cd;
	}

	String getContent_nm() {
		return content_nm;
	}

	void setContent_nm(String content_nm) {
		this.content_nm = content_nm;
	}

	String getContent_rmk() {
		return content_rmk;
	}

	void setContent_rmk(String content_rmk) {
		this.content_rmk = content_rmk;
	}

	public String getSearch() {
		return search;
	}

	public void setSearch(String search) {
		this.search = search;
	}

	public String getCd() {
		return cd;
	}

	public void setCd(String cd) {
		this.cd = cd;
	}

	public String getNm() {
		return nm;
	}

	public void setNm(String nm) {
		this.nm = nm;
	}
	
	
}