package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbbsTmpDocInf;

/**
 * TbbsTmpDocInf - ValueObject Extended class for table [TBBS_TMP_DOC_INF].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TbbsTmpDocInf extends BaseTbbsTmpDocInf {

}