package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbPdrStafHoStatH;

/**
 * TbPdrStafHoStatH - ValueObject Extended class for table [TB_PDR_STAF_HO_STAT_H].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 05. 21
 */
public class TbPdrStafHoStatH extends BaseTbPdrStafHoStatH {

}