package kr.co.ta9.pandora3.pdsp.dao;

import java.util.List;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.common.dto.DataMap;
import kr.co.ta9.pandora3.pcommon.dto.TdspMnPop;

/**
 * TdspMnPopDao - DAO(Data Access Object) class for table [TDSP_MN_POP].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 15
 */
@Repository
public class TdspMnPopDao extends BaseDao {

	/**
	 * 메인 팝업 조회 (단건)
	 * @param parameterMap
	 * @throws Exception
	 */
	public DataMap selectTdspMnPopInfo(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectOne("TdspMnPop.selectTdspMnPopInfo", parameterMap);
	}
	
	/**
	 * 메인화면 팝업 정보 조회
	 * @param parameterMap
	 * @return String
	 * @throws Exception
	 */	
	public List<TdspMnPop> selectTdspMnPopList(String frnt_yn) throws Exception {
		return getSqlSession().selectList("TdspMnPop.selectTdspMnPopList", frnt_yn);
	}	
	
	/**
	 * 메인화면 팝업 목록 조회 (그리드형)
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public JSONObject selectTdspMnPopGridList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TdspMnPop.selectTdspMnPopGridList", parameterMap);
	}
	

}