package kr.co.ta9.pandora3.meta.dao;

import kr.co.ta9.pandora3.meta.dao.base.BaseTbMetaDbmsVerCdMDao;

import org.springframework.stereotype.Repository;

/**
 * TbMetaDbmsVerCdMDao - DAO(Data Access Object) class for table [TB_META_DBMS_VER_CD_M].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 05. 20
 */
@Repository
public class TbMetaDbmsVerCdMDao extends BaseTbMetaDbmsVerCdMDao {

}