package kr.co.ta9.pandora3.meta.dao;

import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.meta.dao.base.BaseTbMetaCmpnyWrkSysMDao;
import kr.co.ta9.pandora3.pcommon.dto.TbMetaCmpnyWrkSysM;

import java.util.List;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

/**
 * TbMetaCmpnyWrkSysMDao - DAO(Data Access Object) class for table [TB_META_CMPNY_WRK_SYS_M].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 05. 20
 */
@Repository
public class TbMetaCmpnyWrkSysMDao extends BaseTbMetaCmpnyWrkSysMDao {

	/**
	 * 업무시스템 콤보박스 조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public List<TbMetaCmpnyWrkSysM> selectWrkSysList(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("TbMetaCmpnyWrkSysM.selectWrkSysComboList", parameterMap);
	}
	
	/**
	 * 업무시스템 정보 불러오기
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public TbMetaCmpnyWrkSysM selectWrkSysData(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectOne("TbMetaCmpnyWrkSysM.selectWrkSysData", parameterMap);

	}


}