package kr.co.ta9.pandora3.meta.dao;

import kr.co.ta9.pandora3.meta.dao.base.BaseTbMetaCmpnyBasicSettingDDao;

import org.springframework.stereotype.Repository;

/**
 * TbMetaCmpnyBasicSettingDDao - DAO(Data Access Object) class for table [TB_META_CMPNY_BASIC_SETTING_D].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 05. 20
 */
@Repository
public class TbMetaCmpnyBasicSettingDDao extends BaseTbMetaCmpnyBasicSettingDDao {

}