package kr.co.ta9.pandora3.pbbs.dao;

import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pbbs.dao.base.BaseTbbsScdInfDao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

/**
 * TbbsScdInfDao - DAO(Data Access Object) class for table [TBBS_SCD_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TbbsScdInfDao extends BaseTbbsScdInfDao {
	
	/**
	 * 스캐줄 목록 조회
	 * @param  parameterMap
	 * @return JSONObject
	 * @throws Exception
	 */
	public JSONObject selectTbbsScdInfList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TbbsScdInf.selectTbbsScdInfList", parameterMap);
	}
	
}