package kr.co.ta9.pandora3.pbbs.dao;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.pbbs.dao.base.BaseTbbsScdInfDaoTrx;
import kr.co.ta9.pandora3.pcommon.dto.TbbsScdInf;

/**
 * TbbsScdInfDaoTrx - Transactional DAO(Data Access Object) class for table
 * [TBBS_SCD_INF].
 *
 * <pre>
 *  Generated by CodeProcessor. You can freely modify this generated file.
 *  Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TbbsScdInfDaoTrx extends BaseTbbsScdInfDaoTrx {
	
	/**
	 * 스케줄 정보 등록
	 * @param  tbbsScdInf
	 * @return int
	 * @throws Exception
	 */
	public int insertTbbsScdInf(TbbsScdInf tbbsScdInf) throws Exception {
		return getSqlSession().insert("TbbsScdInfTrx.insertTbbsScdInf", tbbsScdInf);
	}
	
	/**
	 * 스케줄 정보 수정
	 * @param  tbbsScdInf
	 * @return int
	 * @throws Exception
	 */
	public int updateTbbsScdInf(TbbsScdInf tbbsScdInf) throws Exception {
		return getSqlSession().update("TbbsScdInfTrx.updateTbbsScdInf", tbbsScdInf);
	}
	
	/**
	 * 스케줄 정보 삭제
	 * @param  tbbsScdInf
	 * @return int
	 * @throws Exception
	 */
	public int deleteTbbsScdInf(TbbsScdInf tbbsScdInf) throws Exception {
		return getSqlSession().delete("TbbsScdInfTrx.deleteTbbsScdInf", tbbsScdInf);
	}
	
}