package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTdspSysInf;

/**
 * TdspSysInf - ValueObject Extended class for table [TDSP_SYS_INF].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TdspSysInf extends BaseTdspSysInf {
	private String f_crt_dttm;

	public String getF_crt_dttm() {
		return f_crt_dttm;
	}

	public void setF_crt_dttm(String f_crt_dttm) {
		this.f_crt_dttm = f_crt_dttm;
	}
}