package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTsysAdmRolRtnn;

/**
 * TsysAdmRolRtnn - ValueObject Extended class for table [TSYS_ADM_ROL_RTNN].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TsysAdmRolRtnn extends BaseTsysAdmRolRtnn {
	private String apl_st_dt;
	private String apl_ed_dt;
	private String f_apl_st_dt;
	private String f_apl_ed_dt;
	private String f_crt_dttm;
	private String f_upd_dttm;
	private String rol_nm;
	private String usr_nm;
	
	
	public String getF_apl_st_dt() {
		return f_apl_st_dt;
	}
	public void setF_apl_st_dt(String f_apl_st_dt) {
		this.f_apl_st_dt = f_apl_st_dt;
	}
	public String getF_apl_ed_dt() {
		return f_apl_ed_dt;
	}
	public void setF_apl_ed_dt(String f_apl_ed_dt) {
		this.f_apl_ed_dt = f_apl_ed_dt;
	}
	public String getRol_nm() {
		return rol_nm;
	}
	public void setRol_nm(String rol_nm) {
		this.rol_nm = rol_nm;
	}
	public String getUsr_nm() {
		return usr_nm;
	}
	public void setUsr_nm(String usr_nm) {
		this.usr_nm = usr_nm;
	}
	public String getApl_st_dt() {
		return apl_st_dt;
	}
	public void setApl_st_dt(String apl_st_dt) {
		this.apl_st_dt = apl_st_dt;
	}
	public String getApl_ed_dt() {
		return apl_ed_dt;
	}
	public void setApl_ed_dt(String apl_ed_dt) {
		this.apl_ed_dt = apl_ed_dt;
	}
	public String getF_crt_dttm() {
		return f_crt_dttm;
	}
	public void setF_crt_dttm(String f_crt_dttm) {
		this.f_crt_dttm = f_crt_dttm;
	}
	public String getF_upd_dttm() {
		return f_upd_dttm;
	}
	public void setF_upd_dttm(String f_upd_dttm) {
		this.f_upd_dttm = f_upd_dttm;
	}
	
}