package kr.co.ta9.pandora3.psys.dao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;

/**
 * TsysJobInfDao - DAO(Data Access Object) class for table [TSYS_JOB_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 04
 */
@Repository
public class TsysJobInfDao extends BaseDao {

	/**
	 * 코드 관리 > 직무 조회
	 * @param parameterMap
	 * @return JSONObject
	 * @throws Exception
	 */
	public JSONObject selectTsysJobInfGridList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysJobInf.selectTsysJobInfGridList", parameterMap);
	}

	/**
	 * 직무명 조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public String selectTsysJobInfNms(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectOne("TsysJobInf.selectTsysJobInfNms", parameterMap);
	}

}