package kr.co.ta9.pandora3.psys.dao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TsysAdmMnuRolRtnn;

/**
 * TsysAdmMnuRolRtnnDao - DAO(Data Access Object) class for table [TSYS_ADM_MNU_ROL_RTNN].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TsysAdmMnuRolRtnnDao extends BaseDao {

	/**
	 * 메뉴권한 목록
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public JSONObject selectTsysAdmMnuRolRtnnGridList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysAdmMnuRolRtnn.selectTsysAdmMnuRolRtnnGridList", parameterMap);
	}

	/**
	 * 메뉴 권한 중복체크 조회
	 * @param tsysAdmMnuRolRtnn
	 * @return
	 * @throws Exception
	 */
	public int selectTsysAdmMnuRolRtnnCnt(TsysAdmMnuRolRtnn tsysAdmMnuRolRtnn) throws Exception {
		return getSqlSession().selectOne("TsysAdmMnuRolRtnn.selectTsysAdmMnuRolRtnnCnt", tsysAdmMnuRolRtnn);
	}

}