package kr.co.ta9.pandora3.psys.dao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;

/**
 * TbBcpcMenuacsTotDao - DAO(Data Access Object) class for table [TB_BCPC_MENUACS_TOT].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 04. 07
 */
@Repository
public class TbBcpcMenuacsTotDao extends BaseDao {

	/**
	 * 시스템 통계 메뉴별 클릭 수
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public JSONObject selectTbBcpcMenuacsTotList(ParameterMap parameterMap) throws Exception{
		return queryForGrid("TbBcpcMenuacsTot.selectTbBcpcMenuacsTotList", parameterMap);
	}

}