package kr.co.ta9.pandora3.psys.dao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;

/**
 * TbBcpcLoginTotDao - DAO(Data Access Object) class for table [TB_BCPC_LOGIN_TOT].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 04. 06
 */
@Repository
public class TbBcpcLoginTotDao extends BaseDao {

	/**
	 * 사용자 통계 > 시스템별 접속자 수 
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public JSONObject selectTbBcpcLoginTotList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TbBcpcLoginTot.selectTbBcpcLoginTotList", parameterMap);
	}

	/**
	 * 사용자 통계 > 각 시스템 점별 접속자 수
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public JSONObject selectTbBcpcLoginTotStrList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TbBcpcLoginTot.selectTbBcpcLoginTotStrList", parameterMap);
	}

	
	/**
	 * 점 목록 조회
	 * @param parameterMap
	 * @return
	 */
	public JSONObject selectStrList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TbBcpcLoginTot.selectStrList", parameterMap);
	}

}