package kr.co.ta9.pandora3.psys.dao;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.dao.CommonDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TbBcPcHRrshopbuy;

/**
 * TbBcPcOrgAthrDaoTrx - Transactional DAO(Data Access Object) class for table [TB_BCPC_ORGATHR].
 *
 * <pre>
 *  Generated by CodeProcessor. You can freely modify this generated file.
 *  Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 02. 28
 */
@Repository
public class TbBcPcHRrshopbuyDaoTrx extends CommonDao {

    /**
     * 해당 조직의 소속점 변경
     * @param  parameterMap
     * @throws Exception
     */
    public int updateOrgCstrCd(ParameterMap parameterMap) throws Exception {
        return getSqlSession().update("TbBcPcHRrshopbuyTrx.updateOrgCstrCd", parameterMap);
    }

    /**
     * 해당조직의 직책별 권한 저장
     * @param  parameterMap
     * @throws Exception
     */
    public int insertOrgAthr(ParameterMap parameterMap) throws Exception {
        return getSqlSession().insert("TbBcPcHRrshopbuyTrx.insertOrgAthr", parameterMap);
    }

    /**
     * 해당조직의 직책별 권한 변경
     * @param  parameterMap
     * @throws Exception
     */
    public int updateOrgAthr(ParameterMap parameterMap) throws Exception {
        return getSqlSession().insert("TbBcPcHRrshopbuyTrx.updateOrgAthr", parameterMap);
    }

    /**
     * 매장매입 insert
     * @param  parameterMap
     * @throws Exception
     */
	public int insertTbBcPcHRrshopbuy(TbBcPcHRrshopbuy tbBcPcHRrshopbuy) throws Exception {
		return getSqlSession().insert("TbBcPcHRrshopbuyTrx.insertTbBcPcHRrshopbuy", tbBcPcHRrshopbuy);
	}

	/**
	 * 조직별매장매입관리 > 매장 삭제
	 * @param parameterMap
	 */
	public int deleteTbBcPcHRrshop(ParameterMap parameterMap) throws Exception {
		return getSqlSession().delete("TbBcPcHRrshopbuyTrx.deleteTbBcPcHRrshop", parameterMap);
	}
	
	/**
	 * 조직별매장매입관리 > 매입 삭제
	 * @param parameterMap
	 */
	public int deleteTbBcPcHRrbuy(ParameterMap parameterMap) throws Exception {
		return getSqlSession().delete("TbBcPcHRrshopbuyTrx.deleteTbBcPcHRrbuy", parameterMap);
	}

}