package kr.co.ta9.pandora3.psys.dao;

import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.psys.dao.base.BaseTbLgapVmsprinfschHDao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

/**
 * TbLgapVmsprinfschHDao - DAO(Data Access Object) class for table [TB_LGAP_VMSPRINFSCH_H].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 12. 09
 */
@Repository
public class TbLgapVmsprinfschHDao extends BaseTbLgapVmsprinfschHDao {
	
	

	/**
	 * 이력관리 > vip 메뉴 조회이력
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public JSONObject selectTbLgapVmsprinfschHList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TbLgapVmsprinfschH.selectTbLgapVmsprinfschHList", parameterMap);
	}

}