package kr.co.ta9.pandora3.psys.dao;

import java.util.Map;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;

/**
 * TbLgapMnurtnnHDao - DAO(Data Access Object) class for table [TB_LGAP_MNURTNN_H].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 12. 06
 */
@Repository
public class TbLgapMnurtnnHDao extends BaseDao {

	/**
	 * 사용자 메뉴 매핑 이력 insert
	 * @param tsysAdmMnuRtnnMap
	 * @throws Exception
	 */
	public int insertTbLgapMnurtnnHMap(Map<String, Object> tsysAdmMnuRtnnMap) throws Exception {
		return getSqlSession().insert("TbLgapMnurtnnH.insertTbLgapMnurtnnHMap", tsysAdmMnuRtnnMap);
	}
}