package kr.co.ta9.pandora3.psys.dao;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;

/**
 * TbLgapMnuHDao - DAO(Data Access Object) class for table [TB_LGAP_MNU_H].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 01. 11
 */
@Repository
public class TbLgapMnuHDao extends BaseDao {

}