package kr.co.ta9.pandora3.psys.dao;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;

/**
 * TbLgapPgminfHDao - DAO(Data Access Object) class for table [tb_lgap_pgminf_h].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 01. 13
 */
@Repository
public class TbLgapPgminfHDao extends BaseDao {

}