package kr.co.ta9.pandora3.psys.dao;

import java.util.Map;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;

/**
 * TbLgapRolHDao - DAO(Data Access Object) class for table [TB_LGAP_ROL_H].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 12
 */
@Repository
public class TbLgapRolHDao extends BaseDao {

	/**
	 * 이력 조회 > 권한 변경 이력 조회
	 * @param parameterMap
	 * @return JSONObject
	 * @throws Exception
	 */
	public JSONObject selectTbLgapRolH(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TbLgapRolH.selectTbLgapRolH", parameterMap);
	}
	
	/**
	 * 통합 그룹 권한 이력
	 * @param tbLgapRolHMap
	 * @return
	 */
	public int insertTbLgapRolH(Map<String, Object> tbLgapRolHMap) {
		return getSqlSession().insert("TbLgapRolH.insertTbLgapRolH", tbLgapRolHMap);
	}

}