package kr.co.ta9.pandora3.psys.dao;

import kr.co.ta9.pandora3.psys.dao.base.BaseTbLgapVmsprinfschHDaoTrx;

import org.springframework.stereotype.Repository;

/**
 * TbLgapVmsprinfschHDaoTrx - Transactional DAO(Data Access Object) class for table
 * [TB_LGAP_VMSPRINFSCH_H].
 *
 * <pre>
 *  Generated by CodeProcessor. You can freely modify this generated file.
 *  Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 12. 09
 */
@Repository
public class TbLgapVmsprinfschHDaoTrx extends BaseTbLgapVmsprinfschHDaoTrx {

}