package kr.co.ta9.pandora3.psys.dao;

import java.util.Map;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;

/**
 * TbLgapMnurolrtnnHDao - DAO(Data Access Object) class for table [TB_LGAP_MNUROLRTNN_H].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 12. 02
 */
@Repository
public class TbLgapMnurolrtnnHDao extends BaseDao {
	
	/**
	 * 권한 메뉴 매핑 이력 
	 * @param tsysAdmMnuRolRtnnMap
	 * @return int
	 * @throws Exception
	 */
	public int insertTbLgapMnurolrtnnH(Map<String, Object> tsysAdmMnuRolRtnnMap) throws Exception {
		return getSqlSession().insert("TbLgapMnurolrtnnH.insertTbLgapMnurolrtnnH", tsysAdmMnuRolRtnnMap);
	}

}