package kr.co.ta9.pandora3.psys.dao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;

/**
 * TsysPosInfDao - DAO(Data Access Object) class for table [TSYS_POS_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 05
 */
@Repository
public class TsysPosInfDao extends BaseDao {

	/**
	 * 코드 관리 > 직책 정보 조회
	 * @param parameterMap
	 * @return JSONObject
	 * @throws Exception
	 */
	public JSONObject selectTsysPosInfGridList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysPosInf.selectTsysPosInfGridList", parameterMap);
	}

}