package kr.co.ta9.pandora3.psys.dao;

import kr.co.ta9.pandora3.psys.dao.base.BaseTsysUsrRolDaoTrx;

import org.springframework.stereotype.Repository;

/**
 * TsysUsrRolDaoTrx - Transactional DAO(Data Access Object) class for table
 * [TSYS_USR_ROL].
 *
 * <pre>
 *  Generated by CodeProcessor. You can freely modify this generated file.
 *  Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TsysUsrRolDaoTrx extends BaseTsysUsrRolDaoTrx {
	
}