package kr.co.ta9.pandora3.psys.dao;

import java.util.List;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TsysAdmRol;

/**
 * TsysAdmRolDao - DAO(Data Access Object) class for table [TSYS_ADM_ROL].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TsysAdmRolDao extends BaseDao {

	/**
	 * 권한목록 조회(그리드형)
	 * @param parameterMap
	 * @return JSONObject
	 * @throws Exception
	 */
	public JSONObject selectTsysAdmRolGridList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysAdmRol.selectTsysAdmRolGridList", parameterMap);
	}

	/**
	 * 권한개수 조회
	 * @param parameterMap
	 * @return int
	 * @throws Exception
	 */
	public int selectTsysAdmRolCnt(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectOne("TsysAdmRol.selectTsysAdmRolCnt", parameterMap);
	}

	/**
	 * 권한 목록 조회(일반형)
	 * @param parameterMap
	 * @return
	 */
	public List<TsysAdmRol> selectTsysAdmRolAuthList(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("TsysAdmRol.selectTsysAdmRolAuthList", parameterMap);
	}

	/**
	 * 사이트별 권한 조회
	 * @param parameterMap
	 * @return List<SysCdDtl>
	 * @throws Exception
	 */
	public List<TsysAdmRol> selectRolList(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("TsysAdmRol.selectRolList", parameterMap);
	}

	/**
	 * 로그인 팝업 > 조직 통합 그룹별 권한 조회
	 * @param parameterMap
	 * @return JSONObject
	 * @throws Exception
	 */
	public JSONObject selectTsysAdmOrgGrpRolList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysAdmRol.selectTsysAdmOrgGrpRolList", parameterMap);
	}

	/**
	 * 회원가입 VIP 권한 조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public JSONObject selectVipRolList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysAdmRol.selectRolList", parameterMap);
	}
	
	/**
	 * VIP 신청 가능 권한 목록.
	 * @param parameterMap
	 * @return List<TsysAdmRol>
	 * @throws Exception
	 */
	public List<TsysAdmRol> selectTsysAdmVIPRolList(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("TsysAdmRol.selectTsysAdmVIPRolList", parameterMap);
	}

	/**
	 * 권한 확인 
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public JSONObject selectTmbrAdmLgnInfRolRtnnList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysAdmRol.selectTmbrAdmLgnInfRolRtnnList", parameterMap);
	}

}