package kr.co.ta9.pandora3.psys.dao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.common.dto.DataMap;

/**
 * TsysBatchLogDao - DAO(Data Access Object) class for table [TSYS_BATCH_LOG].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 05. 27
 */
@Repository
public class TsysBatchLogDao extends BaseDao {

	/**
	 * 배치 로그 조회
	 * @param parameterMap
	 * @return JSONObject
	 * @throws Exception
	 */
	public JSONObject selectTsysBatchGridList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysBatchLog.selectTsysBatchGridList", parameterMap);
	}

	/**
	 * 배치 로그 상세 조회
	 * @param parameterMap
	 * @return DataMap
	 * @throws Exception
	 */
	public DataMap selectTsysBatchDetail(ParameterMap parameterMap) throws Exception {
		
		return getSqlSession().selectOne("TsysBatchLog.selectTsysBatchDetail", parameterMap);
	}

}