package kr.co.ta9.pandora3.api.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
/**
 * TbbsDocInfDao - DAO(Data Access Object) class for table [TBBS_DOC_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class ScheduleInfDao extends BaseDao {

	/**
	 * 일정조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public List<Map<String,Object>> selectSchedulenfList(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("ScheduleInf.selectScheduleList", parameterMap);
	}
}
