package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbbsWbznDspDtl;

/**
 * TbbsWbznDspDtl - ValueObject Extended class for table [TBBS_WBZN_DSP_DTL].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TbbsWbznDspDtl extends BaseTbbsWbznDspDtl {
	private String ldg_yn;

	public String getLdg_yn() {
		return ldg_yn;
	}
	public void setLdg_yn(String ldg_yn) {
		this.ldg_yn = ldg_yn;
	}
}