package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.common.bean.BaseBean;

/**
 * TbBchrEmpI - ValueObject Extended class for table [TB_BCHR_EMP_I].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>	
 *
 * @since 2019. 11. 08
 */
public class TbVmcsLngeutlprcoS extends BaseBean {
	
	private String vst_dt;
	private String dt_low;
	private String vat_time;
	private int vst_cust_cnt;
	private int ord_cnt_qty;
	private int lgne_tovrrt;
	private int sty_tm_micnt;
	private int pch_cust_cnt;
	private double drnk_ord_prdc_cnt;
	private double ord_chg_tovrrt;
	private double slng_amt;
	public String getVst_dt() {
		return vst_dt;
	}
	public void setVst_dt(String vst_dt) {
		this.vst_dt = vst_dt;
	}
	public String getDt_low() {
		return dt_low;
	}
	public void setDt_low(String dt_low) {
		this.dt_low = dt_low;
	}
	public String getVat_time() {
		return vat_time;
	}
	public void setVat_time(String vat_time) {
		this.vat_time = vat_time;
	}
	public int getVst_cust_cnt() {
		return vst_cust_cnt;
	}
	public void setVst_cust_cnt(int vst_cust_cnt) {
		this.vst_cust_cnt = vst_cust_cnt;
	}
	public int getOrd_cnt_qty() {
		return ord_cnt_qty;
	}
	public void setOrd_cnt_qty(int ord_cnt_qty) {
		this.ord_cnt_qty = ord_cnt_qty;
	}
	public int getLgne_tovrrt() {
		return lgne_tovrrt;
	}
	public void setLgne_tovrrt(int lgne_tovrrt) {
		this.lgne_tovrrt = lgne_tovrrt;
	}
	public int getSty_tm_micnt() {
		return sty_tm_micnt;
	}
	public void setSty_tm_micnt(int sty_tm_micnt) {
		this.sty_tm_micnt = sty_tm_micnt;
	}
	public int getPch_cust_cnt() {
		return pch_cust_cnt;
	}
	public void setPch_cust_cnt(int pch_cust_cnt) {
		this.pch_cust_cnt = pch_cust_cnt;
	}
	public double getDrnk_ord_prdc_cnt() {
		return drnk_ord_prdc_cnt;
	}
	public void setDrnk_ord_prdc_cnt(double drnk_ord_prdc_cnt) {
		this.drnk_ord_prdc_cnt = drnk_ord_prdc_cnt;
	}
	public double getOrd_chg_tovrrt() {
		return ord_chg_tovrrt;
	}
	public void setOrd_chg_tovrrt(double ord_chg_tovrrt) {
		this.ord_chg_tovrrt = ord_chg_tovrrt;
	}
	public double getSlng_amt() {
		return slng_amt;
	}
	public void setSlng_amt(double slng_amt) {
		this.slng_amt = slng_amt;
	}
	
	
	
	
}