package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTsysAdmMnuRolRtnn;

/**
 * TsysAdmMnuRolRtnn - ValueObject Extended class for table [TSYS_ADM_MNU_ROL_RTNN].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TsysAdmMnuRolRtnn extends BaseTsysAdmMnuRolRtnn {
	private String btn_cd;
	private String mnu_nm;
	private String sys_cd;
	private String sys_nm;
	private String rol_nm;
	
	
	
	public String getMnu_nm() {
		return mnu_nm;
	}
	public void setMnu_nm(String mnu_nm) {
		this.mnu_nm = mnu_nm;
	}
	public String getRol_nm() {
		return rol_nm;
	}
	public void setRol_nm(String rol_nm) {
		this.rol_nm = rol_nm;
	}
	public String getBtn_cd() {
		return btn_cd;
	}
	public void setBtn_cd(String btn_cd) {
		this.btn_cd = btn_cd;
	}
	public String getSys_cd() {
		return sys_cd;
	}
	public void setSys_cd(String sys_cd) {
		this.sys_cd = sys_cd;
	}
	public String getSys_nm() {
		return sys_nm;
	}
	public void setSys_nm(String sys_nm) {
		this.sys_nm = sys_nm;
	}
	
}