package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbbsCtegryDtl;

/**
 * TbbsCtegryDtl - ValueObject Extended class for table [TBBS_CTEGRY_DTL].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 12. 16
 */
public class TbbsCtegryDtl extends BaseTbbsCtegryDtl {
	
	private String f_upd_dttm;

	public String getF_upd_dttm() {
		return f_upd_dttm;
	}

	public void setF_upd_dttm(String f_upd_dttm) {
		this.f_upd_dttm = f_upd_dttm;
	}
	
	

}