package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbbsCtegryMst;

/**
 * TbbsCtegryMst - ValueObject Extended class for table [TBBS_CTEGRY_MST].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 12. 16
 */
public class TbbsCtegryMst extends BaseTbbsCtegryMst {
	private String f_upd_dttm; // 변경날짜
	private String sys_nm;

	public String getSys_nm() {
		return sys_nm;
	}

	public void setSys_nm(String sys_nm) {
		this.sys_nm = sys_nm;
	}

	public String getF_upd_dttm() {
		return f_upd_dttm;
	}

	public void setF_upd_dttm(String f_upd_dttm) {
		this.f_upd_dttm = f_upd_dttm;
	}
	
}