package kr.co.ta9.pandora3.psys.dao;

import java.util.Map;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;

/**
 * TbLgjbAdmlgninfHDao - DAO(Data Access Object) class for table [TB_LGJB_ADMLGNINF_H].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 12. 26
 */
@Repository
public class TbLgjbAdmlgninfHDao extends BaseDao {
	
	/**
	 * 사용자 이력 insert
	 * @param tmbrAdmLgnInfMap
	 * @return 
	 * @throws Exception
	 */
	public int insertTbLgjbAdmlgninfH(Map<String, Object> tmbrAdmLgnInfMap) throws Exception {
		return getSqlSession().insert("TbLgjbAdmlgninfH.insertTbLgjbAdmlgninfH", tmbrAdmLgnInfMap);
	}

}