package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTsysAdmRol;

/**
 * TsysAdmRol - ValueObject Extended class for table [TSYS_ADM_ROL].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TsysAdmRol extends BaseTsysAdmRol {
	private String rol_yn;
	private String usr_id;
	private String f_apl_st_dt;
	private String f_apl_ed_dt;
	private String f_upd_dttm;
	private String sys_cd;		//시스템(사이트) 번호
	private String sys_nm;		// 사이트 이름
	private String appl_stat_cd;
	private String org_cd;
	private String org_nm;
	private String usr_nm;
	private String sys_pth;
	private String sys_abrv;
	private String rol_cl_nm;
	
	

	public String getRol_cl_nm() {
		return rol_cl_nm;
	}
	public void setRol_cl_nm(String rol_cl_nm) {
		this.rol_cl_nm = rol_cl_nm;
	}
	public String getHr_org_nm() {
		return org_nm;
	}
	public void setHr_org_nm(String org_nm) {
		this.org_nm = org_nm;
	}
	public String getUsr_nm() {
		return usr_nm;
	}
	public void setUsr_nm(String usr_nm) {
		this.usr_nm = usr_nm;
	}
	public String getHr_org_cd() {
		return org_cd;
	}
	public void setHr_org_cd(String org_cd) {
		this.org_cd = org_cd;
	}
	public String getAppl_stat_cd() {
		return appl_stat_cd;
	}
	public void setAppl_stat_cd(String appl_stat_cd) {
		this.appl_stat_cd = appl_stat_cd;
	}
	public String getF_upd_dttm() {
		return f_upd_dttm;
	}
	public void setF_upd_dttm(String f_upd_dttm) {
		this.f_upd_dttm = f_upd_dttm;
	}

	public String getRol_yn() {
		return rol_yn;
	}
	public void setRol_yn(String rol_yn) {
		this.rol_yn = rol_yn;
	}

	public String getUsr_id() {
		return usr_id;
	}
	public void setUsr_id(String usr_id) {
		this.usr_id = usr_id;
	}

	public String getF_apl_st_dt() {
		return f_apl_st_dt;
	}
	public void setF_apl_st_dt(String f_apl_st_dt) {
		this.f_apl_st_dt = f_apl_st_dt;
	}

	public String getF_apl_ed_dt() {
		return f_apl_ed_dt;
	}
	public void setF_apl_ed_dt(String f_apl_ed_dt) {
		this.f_apl_ed_dt = f_apl_ed_dt;
	}
	public String getSit_pth() {
		return sys_pth;
	}
	public void setSit_pth(String sys_pth) {
		this.sys_pth = sys_pth;
	}
	public String getSit_abbr() {
		return sys_abrv;
	}
	public void setSit_abbr(String sys_abrv) {
		this.sys_abrv = sys_abrv;
	}
	public String getSys_cd() {
		return sys_cd;
	}
	public void setSys_cd(String sys_cd) {
		this.sys_cd = sys_cd;
	}
	public String getSys_nm() {
		return sys_nm;
	}
	public void setSys_nm(String sys_nm) {
		this.sys_nm = sys_nm;
	}
	

}