package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbLgjbAdmlgninfH;

/**
 * TbLgjbAdmlgninfH - ValueObject Extended class for table [TB_LGJB_ADMLGNINF_H].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 12. 26
 */
public class TbLgjbAdmlgninfH extends BaseTbLgjbAdmlgninfH {

}