package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbLgapAthrappH;

/**
 * TbLgapAthrappH - ValueObject Extended class for table [TB_LGAP_ATHRAPP_H].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 05
 */
public class TbLgapAthrappH extends BaseTbLgapAthrappH {

	private String f_crt_dttm;
	private String f_apvl_dttm;
	

	public String getF_apvl_dttm() {
		return f_apvl_dttm;
	}

	public void setF_apvl_dttm(String f_apvl_dttm) {
		this.f_apvl_dttm = f_apvl_dttm;
	}

	public String getF_crt_dttm() {
		return f_crt_dttm;
	}

	public void setF_crt_dttm(String f_crt_dttm) {
		this.f_crt_dttm = f_crt_dttm;
	}
	
	
}