package kr.co.ta9.pandora3.psys.dao;

import java.util.List;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TsysAdmGrpRolRtnn;

/**
 * TsysAdmGrpRolRtnnDao - DAO(Data Access Object) class for table [TSYS_ADM_GRP_ROL_RTNN].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 10. 28
 */
@Repository
public class TsysAdmGrpRolRtnnDao extends BaseDao {

	/**
	 * 시스템 권한 그룹 권한 목록 조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public JSONObject selectTsysAdmGrpRolRtnnGridList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysAdmGrpRolRtnn.selectTsysAdmGrpRolRtnnGridList", parameterMap);
	}

	/**
	 * 권한 그룹 리스트
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public List<TsysAdmGrpRolRtnn> selectTsysAdmGrpRolRtnnList(TsysAdmGrpRolRtnn tsysAdmGrpRolRtnn) throws Exception {
		return getSqlSession().selectList("TsysAdmGrpRolRtnn.selectTsysAdmGrpRolRtnnList", tsysAdmGrpRolRtnn);
	}

	/**
	 * 권한 그룹 매핑 단건 조회
	 * @param tsysAdmGrpRolRtnn
	 * @return
	 */
	public TsysAdmGrpRolRtnn selectTsysAdmGrpRolRtnn(TsysAdmGrpRolRtnn tsysAdmGrpRolRtnn) {
		return getSqlSession().selectOne("TsysAdmGrpRolRtnn.selectTsysAdmGrpRolRtnn", tsysAdmGrpRolRtnn);

	}
	/**
	 * 시스템권한목록 조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public JSONObject selectRolListAll(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysAdmGrpRolRtnn.selectTsysRolListAll", parameterMap);
	}

	/**
	 * 통합그룹 시스템 그룹 매핑 조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public List<ParameterMap>   selectTsysAdmGrpRolList(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("TsysAdmGrpRolRtnn.selectTsysAdmGrpRolList", parameterMap);
	}
	
	
	/*
	 * 매핑된 권한 삭제
	 */
	public int deleteGrpId(TsysAdmGrpRolRtnn tsysAdmGrpRolRtnn) throws Exception {
		 return getSqlSession().delete("TsysAdmGrpRolRtnn.deleteGrpId", tsysAdmGrpRolRtnn);
	}
	
	/*
	 * 시스템 권한 매핑 등록
	 */
	public int insertGrpRolRtnn(TsysAdmGrpRolRtnn tsysAdmGrpRolRtnn) throws Exception {
		return getSqlSession().insert("TsysAdmGrpRolRtnn.insertGrpRolRtnn", tsysAdmGrpRolRtnn);
	}


}