package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbLgapRolH;

/**
 * TbLgapRolH - ValueObject Extended class for table [TB_LGAP_ROL_H].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 12
 */
public class TbLgapRolH extends BaseTbLgapRolH {
	
	private String f_crt_dttm;

	public String getF_crt_dttm() {
		return f_crt_dttm;
	}

	public void setF_crt_dttm(String f_crt_dttm) {
		this.f_crt_dttm = f_crt_dttm;
	}

}