package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbLgapMnuH;

/**
 * TbLgapMnuH - ValueObject Extended class for table [TB_LGAP_MNU_H].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 01. 11
 */
public class TbLgapMnuH extends BaseTbLgapMnuH {

}