package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTsysAdmGrpRolRtnn;

/**
 * TsysAdmGrpRolRtnn - ValueObject Extended class for table [TSYS_ADM_GRP_ROL_RTNN].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 10. 28
 */
public class TsysAdmGrpRolRtnn extends BaseTsysAdmGrpRolRtnn {
	
	private String usr_id;                 // 사용자 아이디
	private String grp_rol_nm;             // 그룹 권한 이름
    private String bdp_rol;                // bdp 사이트 권한
    private String ams_rol;                // ams 사이트 권한
    private String vip_rol;                // vip 사이트 권한
    private String trd_rol;                // trd 사이트 권한
    private String mlo_rol;                // mlo 사이트 권한
    private String bpn_rol;                // bpn 사이트 권한
    private String cms_rol;                // cms 사이트 권한
    private String bi_rol;                 // bi  사이트 권한
    private String grp_rol_ids;            // 그룹 권한 패핑 권한들
    private String rol_nm;                 // 권한 이름
    private String sys_cd;                   // 사이트번호
    private String sys_nm;                 // 사이트명
    
    //getter, setter 
    
    
    public String getUsr_id() {
    	return usr_id;
    }
    public String getRol_nm() {
		return rol_nm;
	}
	public void setRol_nm(String rol_nm) {
		this.rol_nm = rol_nm;
	}
	public String getCms_rol() {
		return cms_rol;
	}
	public void setCms_rol(String cms_rol) {
		this.cms_rol = cms_rol;
	}
	public String getBi_rol() {
		return bi_rol;
	}
	public void setBi_rol(String bi_rol) {
		this.bi_rol = bi_rol;
	}
	public void setUsr_id(String usr_id) {
    	this.usr_id = usr_id;
    }
	public String getGrp_rol_nm() {
		return grp_rol_nm;
	}
	public String getGrp_rol_ids() {
		return grp_rol_ids;
	}
	public void setGrp_rol_ids(String grp_rol_ids) {
		this.grp_rol_ids = grp_rol_ids;
	}
	public void setGrp_rol_nm(String grp_rol_nm) {
		this.grp_rol_nm = grp_rol_nm;
	}
	public String getBdp_rol() {
		return bdp_rol;
	}
	public void setBdp_rol(String bdp_rol) {
		this.bdp_rol = bdp_rol;
	}
	public String getAms_rol() {
		return ams_rol;
	}
	public void setAms_rol(String ams_rol) {
		this.ams_rol = ams_rol;
	}
	public String getVip_rol() {
		return vip_rol;
	}
	public void setVip_rol(String vip_rol) {
		this.vip_rol = vip_rol;
	}
	public String getTrd_rol() {
		return trd_rol;
	}
	public void setTrd_rol(String trd_rol) {
		this.trd_rol = trd_rol;
	}
	public String getMlo_rol() {
		return mlo_rol;
	}
	public void setMlo_rol(String mlo_rol) {
		this.mlo_rol = mlo_rol;
	}
	public String getBpn_rol() {
		return bpn_rol;
	}
	public void setBpn_rol(String bpn_rol) {
		this.bpn_rol = bpn_rol;
	}
	public String getSys_cd() {
		return sys_cd;
	}
	public void setSys_cd(String sys_cd) {
		this.sys_cd = sys_cd;
	}
	public String getSys_nm() {
		return sys_nm;
	}
	public void setSys_nm(String sys_nm) {
		this.sys_nm = sys_nm;
	}

}