package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTsysBatchLog;

/**
 * TsysBatchLog - ValueObject Extended class for table [TSYS_BATCH_LOG].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 05. 27
 */
public class TsysBatchLog extends BaseTsysBatchLog {
	
	private String f_batch_wrk_st_dt;
	private String f_batch_wrk_ed_dt;
	private String f_batch_st_dt;
	private String f_batch_ed_dt;
	
	
	public String getF_batch_wrk_st_dt() {
		return f_batch_wrk_st_dt;
	}
	public void setF_batch_wrk_st_dt(String f_batch_wrk_st_dt) {
		this.f_batch_wrk_st_dt = f_batch_wrk_st_dt;
	}
	public String getF_batch_wrk_ed_dt() {
		return f_batch_wrk_ed_dt;
	}
	public void setF_batch_wrk_ed_dt(String f_batch_wrk_ed_dt) {
		this.f_batch_wrk_ed_dt = f_batch_wrk_ed_dt;
	}
	public String getF_batch_st_dt() {
		return f_batch_st_dt;
	}
	public void setF_batch_st_dt(String f_batch_st_dt) {
		this.f_batch_st_dt = f_batch_st_dt;
	}
	public String getF_batch_ed_dt() {
		return f_batch_ed_dt;
	}
	public void setF_batch_ed_dt(String f_batch_ed_dt) {
		this.f_batch_ed_dt = f_batch_ed_dt;
	}
	
	
	

}