package kr.co.ta9.pandora3.pwzn.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TbbsWbznDspDtl;
import kr.co.ta9.pandora3.pwzn.dao.base.BaseTbbsWbznDspDtlDao;

/**
 * TbbsWbznDspDtlDao - DAO(Data Access Object) class for table [TBBS_WBZN_DSP_DTL].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TbbsWbznDspDtlDao extends BaseTbbsWbznDspDtlDao {
	
	/**
	 * 인사이트 상세 목록 조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public List<TbbsWbznDspDtl> selectTbbsWbznDspDtlList (ParameterMap parameterMap) throws Exception{
		return getSqlSession().selectList("TbbsWbznDspDtl.selectTbbsWbznDspDtlList", parameterMap);
	}
}