package kr.co.ta9.pandora3.pwzn.dao;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.pwzn.dao.base.BaseTbbsWbznDspMnInfDaoTrx;

/**
 * TbbsWbznDspMnInfDaoTrx - Transactional DAO(Data Access Object) class for table
 * [TBBS_WBZN_DSP_MN_INF].
 *
 * <pre>
 *  Generated by CodeProcessor. You can freely modify this generated file.
 *  Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TbbsWbznDspMnInfDaoTrx extends BaseTbbsWbznDspMnInfDaoTrx {
	
}