package kr.co.ta9.pandora3.pwzn.dao;

import java.util.List;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TbbsWbznDspMnInf;
import kr.co.ta9.pandora3.pwzn.dao.base.BaseTbbsWbznDspMnInfDao;

/**
 * TbbsWbznDspMnInfDao - DAO(Data Access Object) class for table [TBBS_WBZN_DSP_MN_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TbbsWbznDspMnInfDao extends BaseTbbsWbznDspMnInfDao {
	
	/**
	 * 웹진 메인 목록 조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public List<TbbsWbznDspMnInf> selectTbbsWbznDspMnInfList (ParameterMap parameterMap) throws Exception{
		return getSqlSession().selectList("TbbsWbznDspMnInf.selectTbbsWbznDspMnInfList", parameterMap);
	}
	
	/**
	 * 웹진 목록 조회(메인카테고리 - 상세컨텐츠 매핑여부 포함)
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public List<TbbsWbznDspMnInf> selectTbbsWbznDspMnInfInitList(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("TbbsWbznDspMnInf.selectTbbsWbznDspMnInfInitList", parameterMap);
	}
	
}