package kr.co.ta9.pandora3.psys.dao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TsysPgmInf;

/**
 * TsysPgmInfDao - DAO(Data Access Object) class for table [TSYS_PGM_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TsysPgmInfDao extends BaseDao {

	/**
	 * 프로그램 리스트 조회
	 * @param parameterMap
	 * @return List<SysPgmInfo>
	 * @throws Exception
	 */
	public JSONObject getTsysPgmInfBtnList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysPgmInf.getTsysPgmInfBtnList", parameterMap);
	}
	
	/**
	 * 조직별 버튼 목록 조회
	 * @param parameterMap
	 * @return List<SysPgmInfo>
	 * @throws Exception
	 */
	public JSONObject getTsysPgmInfBtnOrgList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysPgmInf.getTsysPgmInfBtnOrgList", parameterMap);
	}
	
	/**
	 * 사용자별 버튼 목록 조회
	 * @param parameterMap
	 * @return List<SysPgmInfo>
	 * @throws Exception
	 */
	public JSONObject getTsysPgmInfBtnUsrList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysPgmInf.getTsysPgmInfBtnUsrList", parameterMap);
	}
	
	/**
	 * 프로그램 리스트 조회
	 * @param parameterMap
	 * @return List<SysPgmInfo>
	 * @throws Exception
	 */
	public JSONObject getTsysPgmInfList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysPgmInf.getTsysPgmInfList", parameterMap);
	}
	
	/**
	 * 프로그램ID 중복 체크
	 * @param parameterMap
	 * @return List<SysPgmInfo>
	 * @throws Exception
	 */
	public int selectTsysPgmInfCnt(TsysPgmInf tsysPgmInf) throws Exception {
		return getSqlSession().selectOne("TsysPgmInf.selectTsysPgmInfCnt", tsysPgmInf);
	}


}