package kr.co.ta9.pandora3.pcmn.dao;

import java.util.List;
import java.util.Map;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TcmnPopupInf;
/**
 * TcmnPopupInfDao - DAO(Data Access Object) class for table [TCMN_POPUP_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TcmnPopupInfDao extends BaseDao {
	
//	private NamedParameterJdbcTemplate jdbcTemplate;
//	
//	@Resource(name="dataSourceCommon")
//	public void setDataSource(DataSource dataSource) {
//		this.jdbcTemplate = new NamedParameterJdbcTemplate(dataSource);
//	}
	
	/**
	 * 공통 팝업  그리드 설정 값 조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public TcmnPopupInf selectTcmnPopupInfGrid(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectOne("TcmnPopupInf.selectTcmnPopupInfGrid", parameterMap);
	}

	/**
	 * 공통 팝업  그리드 조회를 위한 쿼리 절 조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public TcmnPopupInf selectTcmnPopupInfInfo(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectOne("TcmnPopupInf.selectTcmnPopupInfInfo", parameterMap);
	}

	/**
	 * 공통 팝업 조회
	 * @param query
	 * @param parameterMap
	 * @return
	 */
	public List<Map<String, Object>> selectCommonPopupList(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("TcmnPopupInf.selectCommonPopupList", parameterMap);
	}

	/**
	 * 공통팝업관리 조회
	 * @param parameterMap
	 * @return SysUserLogin
	 * @throws Exception
	 */
	public JSONObject selectTcmnPopupInfList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TcmnPopupInf.selectTcmnPopupInfList", parameterMap);
	}
	
	/**
	 * 공통 팝업  관리 중복체크
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public int selectTcmnPopupInfCnt(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectOne("TcmnPopupInf.selectTcmnPopupInfCnt", parameterMap);
	}

}