package kr.co.ta9.pandora3.pmbr.dao;

import java.util.List;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TmbrClu;

/**
 * TmbrCluDao - DAO(Data Access Object) class for table [TMBR_CLU].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TmbrCluDao extends BaseDao {

	/**
	 * 약관 조회 (그리드형)
	 * @param parameterMap
	 * @return JSONObject
	 * @throws Exception
	 */
	public JSONObject getTmbrCluList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TmbrClu.getTmbrCluList", parameterMap);
	}

	/**
	 * 약관 코드 조회
	 * @param parameterMap
	 * @return JSONObject
	 * @throws Exception
	 */
	public List<TmbrClu> getTmbrCluCode(ParameterMap parameterMap) throws Exception{
		return getSqlSession().selectList("TmbrClu.getTmbrCluCode",parameterMap);
	}

	/**
	 * 약관 존재여부조회
	 * @param parameterMap
	 * @return String
	 * @throws Exception
	 */
	public String getTmbrCluExistYN(ParameterMap parameterMap) throws Exception{
		return getSqlSession().selectOne("TmbrClu.getTmbrCluExistYN",parameterMap);
	}
	
	/**
	 * @param tmbrClu TmbrClu
	 * @throws Exception
	 */
	public  int insertTmbrCluHst(TmbrClu tmbrClu) throws Exception {
		return getSqlSession().insert("TmbrClu.insertTmbrCluHst", tmbrClu);
	}

}