package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbBcpcMenuacsTot;

/**
 * TbBcpcMenuacsTot - ValueObject Extended class for table [TB_BCPC_MENUACS_TOT].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 04. 07
 */
public class TbBcpcMenuacsTot extends BaseTbBcpcMenuacsTot {
	
	private String menu_acs;
	private String menu_vst_cust_cnt;
	private String depth_fullname;
	private String uv_vst_cust_cnt;
	private String sys_nm;
	
	public String getMenu_acs() {
		return menu_acs;
	}
	public void setMenu_acs(String menu_acs) {
		this.menu_acs = menu_acs;
	}
	public String getMenu_vst_cust_cnt() {
		return menu_vst_cust_cnt;
	}
	public void setMenu_vst_cust_cnt(String menu_vst_cust_cnt) {
		this.menu_vst_cust_cnt = menu_vst_cust_cnt;
	}
	public String getDepth_fullname() {
		return depth_fullname;
	}
	public void setDepth_fullname(String depth_fullname) {
		this.depth_fullname = depth_fullname;
	}
	public String getUv_vst_cust_cnt() {
		return uv_vst_cust_cnt;
	}
	public void setUv_vst_cust_cnt(String uv_vst_cust_cnt) {
		this.uv_vst_cust_cnt = uv_vst_cust_cnt;
	}
	public String getSys_nm() {
		return sys_nm;
	}
	public void setSys_nm(String sys_nm) {
		this.sys_nm = sys_nm;
	}
	
}