package kr.co.ta9.pandora3.pbbs.dao;

import kr.co.ta9.pandora3.pbbs.dao.base.BaseTbbsDocAddItmInfDao;

import org.springframework.stereotype.Repository;

/**
 * TbbsDocAddItmInfDao - DAO(Data Access Object) class for table [TBBS_DOC_ADD_ITM_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TbbsDocAddItmInfDao extends BaseTbbsDocAddItmInfDao {

}