package kr.co.ta9.pandora3.psys.dao;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.psys.dao.base.BaseTsysAdmOrgGrpRolRtnnDaoTrx;

/**
 * TsysAdmOrgGrpRolRtnnDaoTrx - Transactional DAO(Data Access Object) class for table
 * [TSYS_ADM_ORG_GRP_ROL_RTNN].
 *
 * <pre>
 *  Generated by CodeProcessor. You can freely modify this generated file.
 *  Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 10. 29
 */
@Repository
public class TsysAdmOrgGrpRolRtnnDaoTrx extends BaseTsysAdmOrgGrpRolRtnnDaoTrx {

	/**
	 * 조직 권한 그룹 추가
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public int saveTsysAdmOrgGrpRolRtnn(ParameterMap parameterMap) throws Exception {
		return getSqlSession().insert("TsysAdmOrgGrpRolRtnnTrx.saveTsysAdmOrgGrpRolRtnn", parameterMap);
	}

	public int deleteTsysAdmOrgGrpRolRtnn(ParameterMap parameterMap) throws Exception {
		return getSqlSession().delete("TsysAdmOrgGrpRolRtnnTrx.deleteTsysAdmOrgGrpRolRtnn", parameterMap);
	}

}