package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTdspTmplInf;

/**
 * TdspTmplInf - ValueObject Extended class for table [TDSP_TMPL_INF].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TdspTmplInf extends BaseTdspTmplInf {

	private String tmpl_tp_cd_nm;
	private String mnu_nm;
	private String up_mnu_nm;
	private String up_tmpl_nm;
	private String mapped_yn;
	private int up_dsply_no;
	private String up_tmpl_tp_cd;
	private String mnu_yn;
	private String mnu_tp_cd;
	private String up_tmpl_url;
	private String mnu_dpth;
	private String stf_only_yn;
	private String url;
	
	

	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	// oracle, mssql 변수
	private String del_modl_yn;
	private String edt_dsplyNo_yn;
	
	public String getStf_only_yn() {
		return stf_only_yn;
	}
	public void setStf_only_yn(String stf_only_yn) {
		this.stf_only_yn = stf_only_yn;
	}
	
	public String getMnu_dpth() {
		return mnu_dpth;
	}
	public void setMnu_dpth(String mnu_dpth) {
		this.mnu_dpth = mnu_dpth;
	}
	public String getTmpl_tp_cd_nm() {
		return tmpl_tp_cd_nm;
	}
	public void setTmpl_tp_cd_nm(String tmpl_tp_cd_nm) {
		this.tmpl_tp_cd_nm = tmpl_tp_cd_nm;
	}
	public String getMnu_nm() {
		return mnu_nm;
	}
	public void setMnu_nm(String mnu_nm) {
		this.mnu_nm = mnu_nm;
	}
	public String getUp_mnu_nm() {
		return up_mnu_nm;
	}
	public void setUp_mnu_nm(String up_mnu_nm) {
		this.up_mnu_nm = up_mnu_nm;
	}
	public String getUp_tmpl_nm() {
		return up_tmpl_nm;
	}
	public void setUp_tmpl_nm(String up_tmpl_nm) {
		this.up_tmpl_nm = up_tmpl_nm;
	}
	public String getMapped_yn() {
		return mapped_yn;
	}
	public void setMapped_yn(String mapped_yn) {
		this.mapped_yn = mapped_yn;
	}
	public int getUp_dsply_no() {
		return up_dsply_no;
	}
	public void setUp_dsply_no(int up_dsply_no) {
		this.up_dsply_no = up_dsply_no;
	}
	public String getUp_tmpl_tp_cd() {
		return up_tmpl_tp_cd;
	}
	public void setUp_tmpl_tp_cd(String up_tmpl_tp_cd) {
		this.up_tmpl_tp_cd = up_tmpl_tp_cd;
	}
	public String getMnu_yn() {
		return mnu_yn;
	}
	public void setMnu_yn(String mnu_yn) {
		this.mnu_yn = mnu_yn;
	}
	public String getMnu_tp_cd() {
		return mnu_tp_cd;
	}
	public void setMnu_tp_cd(String mnu_tp_cd) {
		this.mnu_tp_cd = mnu_tp_cd;
	}
	public String getUp_tmpl_url() {
		return up_tmpl_url;
	}
	public void setUp_tmpl_url(String up_tmpl_url) {
		this.up_tmpl_url = up_tmpl_url;
	}
	public String getDel_modl_yn() {
		return del_modl_yn;
	}
	public void setDel_modl_yn(String del_modl_yn) {
		this.del_modl_yn = del_modl_yn;
	}
	public String getEdt_dsplyNo_yn() {
		return edt_dsplyNo_yn;
	}
	public void setEdt_dsplyNo_yn(String edt_dsplyNo_yn) {
		this.edt_dsplyNo_yn = edt_dsplyNo_yn;
	}
}