package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.common.bean.BaseBean;

/**
 * TbBchrEmpI - ValueObject Extended class for table [TB_BCHR_EMP_I].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 08
 */
public class TbAmaiDstrbzarvstD extends BaseBean {

    private int srt_seq; 
    private int rvco_srno;
    private String nm;     //이름
    private int col_cnt1;  //14일전
    private int col_cnt2;  //13일전
    private int col_cnt3;  //12일전
    private int col_cnt4;  //11일전
    private int col_cnt5;  //10일전
    private int col_cnt6;  //9일전
    private int col_cnt7;  //8일전
    private int col_cnt8;  //7일전
    private int col_cnt9;  //6일전
    private int col_cnt10; //5일전
    private int col_cnt11; //4일전    2달전
    private int col_cnt12; //3일전 , 1달전
    private int col_cnt13; //2일전 , 현재 달 
    private int col_cnt14; //1일전
	public int getSrt_seq() {
		return srt_seq;
	}
	public void setSrt_seq(int srt_seq) {
		this.srt_seq = srt_seq;
	}
	public int getRvco_srno() {
		return rvco_srno;
	}
	public void setRvco_srno(int rvco_srno) {
		this.rvco_srno = rvco_srno;
	}
	public String getNm() {
		return nm;
	}
	public void setNm(String nm) {
		this.nm = nm;
	}
	public int getCol_cnt1() {
		return col_cnt1;
	}
	public void setCol_cnt1(int col_cnt1) {
		this.col_cnt1 = col_cnt1;
	}
	public int getCol_cnt2() {
		return col_cnt2;
	}
	public void setCol_cnt2(int col_cnt2) {
		this.col_cnt2 = col_cnt2;
	}
	public int getCol_cnt3() {
		return col_cnt3;
	}
	public void setCol_cnt3(int col_cnt3) {
		this.col_cnt3 = col_cnt3;
	}
	public int getCol_cnt4() {
		return col_cnt4;
	}
	public void setCol_cnt4(int col_cnt4) {
		this.col_cnt4 = col_cnt4;
	}
	public int getCol_cnt5() {
		return col_cnt5;
	}
	public void setCol_cnt5(int col_cnt5) {
		this.col_cnt5 = col_cnt5;
	}
	public int getCol_cnt6() {
		return col_cnt6;
	}
	public void setCol_cnt6(int col_cnt6) {
		this.col_cnt6 = col_cnt6;
	}
	public int getCol_cnt7() {
		return col_cnt7;
	}
	public void setCol_cnt7(int col_cnt7) {
		this.col_cnt7 = col_cnt7;
	}
	public int getCol_cnt8() {
		return col_cnt8;
	}
	public void setCol_cnt8(int col_cnt8) {
		this.col_cnt8 = col_cnt8;
	}
	public int getCol_cnt9() {
		return col_cnt9;
	}
	public void setCol_cnt9(int col_cnt9) {
		this.col_cnt9 = col_cnt9;
	}
	public int getCol_cnt10() {
		return col_cnt10;
	}
	public void setCol_cnt10(int col_cnt10) {
		this.col_cnt10 = col_cnt10;
	}
	public int getCol_cnt11() {
		return col_cnt11;
	}
	public void setCol_cnt11(int col_cnt11) {
		this.col_cnt11 = col_cnt11;
	}
	public int getCol_cnt12() {
		return col_cnt12;
	}
	public void setCol_cnt12(int col_cnt12) {
		this.col_cnt12 = col_cnt12;
	}
	public int getCol_cnt13() {
		return col_cnt13;
	}
	public void setCol_cnt13(int col_cnt13) {
		this.col_cnt13 = col_cnt13;
	}
	public int getCol_cnt14() {
		return col_cnt14;
	}
	public void setCol_cnt14(int col_cnt14) {
		this.col_cnt14 = col_cnt14;
	}
	
}