package kr.co.ta9.pandora3.pbbs.dao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TbbsDocInf;

/**
 * TbbsDocInfDao - DAO(Data Access Object) class for table [TBBS_DOC_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class Pbbs4001Dao extends BaseDao {
	
	/**
	 * 공지사항 목록 조회
	 * @param  parameterMap
	 * @return SysDocument
	 * @throws Exception
	 */
	public JSONObject selectNoticeList(ParameterMap parameterMap) throws Exception { 
		return queryForGrid("TbbsDocInf.getTbbsDocInfNoticeLandingList", parameterMap);
	}
	
	/**
	 * 공지사항 상세 조회
	 * @param  parameterMap
	 * @return SysDocument
	 * @throws Exception
	 */
	public TbbsDocInf selectNoticeDtl(ParameterMap parameterMap) throws Exception { 
		return getSqlSession().selectOne("Pbbs4001.selectNoticeDtl", parameterMap);
	}
	
	/**
	 * 카테고리 목록 조회
	 * @param  parameterMap
	 * @return SysDocument
	 * @throws Exception
	 */
	public JSONObject selectBoardCtgList2(ParameterMap parameterMap) throws Exception { 
		return queryForGrid("Pbbs4001.selectBoardCtgList2", parameterMap);
	}
	
	/**
	 * 게시판 명 검색조건 조회
	 * @param  parameterMap
	 * @return SysDocument
	 * @throws Exception
	 */
	public JSONObject getModlNm(ParameterMap parameterMap) throws Exception { 
		return queryForGrid("Pbbs4001.getModlNm", parameterMap);
	}
	
	/**
	 * 공지사항 제목,내용 조회
	 * @param  parameterMap
	 * @return SysDocument
	 * @throws Exception
	 */
	public JSONObject getDocInfo(ParameterMap parameterMap) throws Exception { 
		return queryForGrid("Pbbs4001.getDocInfo", parameterMap);
	}
	
}