package kr.co.ta9.pandora3.pbbs.dao;

import java.util.List;
import java.util.Map;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.Pbbs5001VO;

/**
 * TbbsWikiDocInfDao - DAO(Data Access Object) class for table [TBBS_WIKI_DOC_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 04. 07
 */
@Repository
public class TbbsWikiDocInfDao extends BaseDao {

	/**
	 * 위키 카테고리 별 게시글 목록 조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public JSONObject getPbbs5001GridList01(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TbbsWikiDocInf.getPbbs5001GridList01", parameterMap);
	}

	/**
	 * 위키 신규 wiki_doc_seq 조회
	 * @return
	 * @throws Exception
	 */
	public int getPbbs5002BbsSrno() throws Exception {
		return getSqlSession().selectOne("TbbsWikiDocInf.getPbbs5002Bbssrno");
	}

	/**
	 * 위키 메뉴얼 상세 정보 조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public Map<String, Object> getPbbs5003BbsOne(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectOne("TbbsWikiDocInf.getPbbs5003BbsOne", parameterMap);
	}

	/**
	 * 위키 메뉴얼 상세 정보 조회(프론트 용)
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public Pbbs5001VO getPbbs5004BbsOneFront(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectOne("TbbsWikiDocInf.getPbbs5004BbsOneFront", parameterMap);
	}

	/**
	 * 위키 메뉴얼 기본 목록 조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public List<Map<String, Object>> getPbbs5004BbsDefault(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("TbbsWikiDocInf.getPbbs5004BbsDefault", parameterMap);
	}

	/**
	 * 다음글 이전글 조회
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public List<Pbbs5001VO> getPbbs5004BbsFrontPrvNxt(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("TbbsWikiDocInf.getPbbs5004BbsFrontPrvNxt", parameterMap);
	}
	
	/**
	 * 위키 게시글 등록
	 * @param parameterMap
	 * @throws Exception
	 */
	public int insertPbbs5002One(ParameterMap parameterMap) throws Exception {
		return getSqlSession().insert("TbbsWikiDocInf.insertPbbs5002One", parameterMap);
	}

	/**
	 * 위키 게시글 수정
	 * @param parameterMap
	 * @throws Exception
	 */
	public int updatePbbs5002One(ParameterMap parameterMap) throws Exception {
		return getSqlSession().update("TbbsWikiDocInf.updatePbbs5002One", parameterMap);
	}

	/**
	 * 위키 게시글 조회수 증가
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public int updatePbbsInqCnt(ParameterMap parameterMap) throws Exception {
		return getSqlSession().update("TbbsWikiDocInf.updatePbbsInqCnt", parameterMap);
	}

}