package kr.co.ta9.pandora3.pbbs.dao;

import kr.co.ta9.pandora3.pbbs.dao.base.BaseTbbsTmpDocInfDaoTrx;

import org.springframework.stereotype.Repository;

/**
 * TbbsTmpDocInfDaoTrx - Transactional DAO(Data Access Object) class for table
 * [TBBS_TMP_DOC_INF].
 *
 * <pre>
 *  Generated by CodeProcessor. You can freely modify this generated file.
 *  Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TbbsTmpDocInfDaoTrx extends BaseTbbsTmpDocInfDaoTrx {

}