package kr.co.ta9.pandora3.pbbs.dao;

import java.util.List;
import java.util.Map;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TbbsCtegryDtl;

/**
 * TbbsCtegryDtlDao - DAO(Data Access Object) class for table [TBBS_CTEGRY_DTL].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 12. 16
 */
@Repository
public class TbbsCtegryDtlDao extends BaseDao {
	
	/**
	 * @param tbbsCtegryDtl TbbsCtegryDtl
	 * @return boolean
	 */
	public boolean isPrimaryKeyValid(TbbsCtegryDtl tbbsCtegryDtl) {
		boolean result = true;
		if (tbbsCtegryDtl == null) {
			result = false;
		}

		if (
			tbbsCtegryDtl.getCtegry_dtl_cd()== null
			||
			tbbsCtegryDtl.getCtegry_mst_cd()== null
			) {
			result = false;
		}
		return result;
	}

	/**
	 * 코드 리스트 조회
	 * @param parameterMap
	 * @return List<SysCdDtl>
	 * @throws Exception
	 */
	public List<Map> selectTbbsCtegryDtlList(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("TbbsCtegryDtl.selectTbbsCtegryDtlList", parameterMap);
	}

	/**
	 * 코드상세 리스트 조회 (그리드형)
	 * @param parameterMap
	 * @return JSONObject
	 * @throws Exception
	 */
	public JSONObject selectTbbsCtegryDtlGridList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TbbsCtegryDtl.selectTbbsCtegryDtlGridList", parameterMap);
	}

	/**
	 * 키중복 체크
	 * @param parameterMap
	 * @return int
	 * @throws Exception
	 */

	public int selectTbbsCtegryDtlCnt(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectOne("TbbsCtegryDtl.selectTbbsCtegryDtlCnt", parameterMap);
	}

	/**
	 * 코드 리스트 조회(MST_CD 복수)
	 * @param parameterMap
	 * @return List<SysCdDtl>
	 * @throws Exception
	 */
	public List<TbbsCtegryDtl> selectTbbsCtegryDtlMultiList(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("TbbsCtegryDtl.selectTbbsCtegryDtlMultiList", parameterMap);
	}

	/**
	 * CDNM 중복 체크
	 * @param parameterMap
	 * @return int
	 * @throws Exception
	 */
	public int selectTbbsCtegryDtlCdNm(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectOne("TbbsCtegryDtl.selectTbbsCtegryDtlCdNm", parameterMap);
	}

	public int getTbbsCtegryDtlCDCnt() throws Exception{
		return getSqlSession().selectOne("TbbsCtegryDtl.getTbbsCtegryDtlCDCnt");
	}

}