package kr.co.ta9.pandora3.pbbs.dao;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;

/**
 * TbbsWikiFlInfDao - DAO(Data Access Object) class for table [TBBS_WIKI_FL_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 04. 07
 */
@Repository
public class TbbsWikiFlInfDao extends BaseDao {
	
	
	/**
	 * 위키 메뉴얼 첨부 파일 등록
	 * @param ParameterMap parameterMap
	 * @throws Exception
	 */
	public int insert(ParameterMap parameterMap) throws Exception {
		return getSqlSession().insert("TbbsWikiFlInf.insert", parameterMap);
	}

	/**
	 * 위키 메뉴얼 첨부 파일 삭제
	 * @param ParameterMap parameterMap
	 * @throws Exception
	 */
	public int delete(ParameterMap parameterMap)throws Exception {
		return getSqlSession().insert("TbbsWikiFlInf.delete", parameterMap);
	}
	
	
	/**
	 * 위키 신규 wiki_fl_seq 조회
	 * @return
	 * @throws Exception
	 */
	public int getPbbs5002BbsAtchFleSrno() throws Exception {
		return getSqlSession().selectOne("TbbsWikiFlInf.getPbbs5002BbsAtchFleSrno");
	}

	/**
	 * 위키 wiki_doc_seq 기준 첨부파일 목록
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public List<Map<String, Object>> getPbbs5003Bbsfiles(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("TbbsWikiFlInf.getPbbs5003Bbsfiles", parameterMap);
	}
	
	/**
	 * 위키 메뉴얼 첨부 파일 전체 수정
	 * @param ParameterMap parameterMap
	 * @throws Exception
	 */
	public int updatePbbs5002FleMapping(ParameterMap parameterMap)throws Exception {
		return getSqlSession().update("TbbsWikiFlInf.updatePbbs5002FleMapping", parameterMap);
	}

}