package kr.co.ta9.pandora3.pbbs.dao;

import java.util.List;
import java.util.Map;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.common.util.BeanUtil;
import kr.co.ta9.pandora3.pcommon.dto.TbbsModlInf;

/**
 * TbbsModlInfDao - DAO(Data Access Object) class for table [TBBS_MODL_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TbbsModlInfDao extends BaseDao {
	
	/**
	 * 메인화면 tmpl_seq에 따른 모듈타입 조회
	 * @param 
	 * @return
	 * @throws Exception
	 */
	public List<TbbsModlInf> selectModuleTypeList(List<String> tmpIdList) throws Exception {
		return getSqlSession().selectList("TbbsModlInf.selectModuleTypeList", tmpIdList);
	}

	/**
	 * 메뉴 맵핑여부 판단여부 조회
	 *
	 *
	 */
	public String getTbbsModlInfId(ParameterMap parameterMap) throws Exception{
		return  getSqlSession().selectOne("TbbsModlInf.getTbbsModlInfId",parameterMap);
	}

	/**
	 * 템플릿 매핑 정보 조회
	 *
	 *
	 */

	public JSONObject selectTbbsModlInfMappingList(ParameterMap parameterMap) throws Exception{
	return queryForGrid("TbbsModlInf.selectTbbsModlInfMappingList",parameterMap);

	}

	/**
	 * 모듈 정보 조회
	 * @param  tmpl_seq
	 * @return TbbsModlInf
	 */
	public TbbsModlInf selectTbbsModlInfInfo(String tmpl_seq) {
		return getSqlSession().selectOne("TbbsModlInf.selectTbbsModlInfInfo", tmpl_seq);
	}

	/**
	 * 동영상
	 * BOARD TYPE5 : 동영상 모듈 목록 조회
	 * @param request
	 * @param response
	 * @throws Exception
	 */
	@SuppressWarnings("unchecked")
	public JSONObject selectTbbsModlInfMovieList(ParameterMap parameterMap) throws Exception {
		List<Object> dataList = getSqlSession().selectList("TbbsModlInf.selectTbbsModlInfMovieList", parameterMap);
		List<Map<String,Object>> mapList = BeanUtil.convertObjectToMapList(dataList);
		JSONObject json = new JSONObject();
		json.put("boardModuleList", mapList);
		return json;
	}

	/**
	 * 일반 컨텐츠
	 * BOARD TYPE1/TYPE2 : 게시판 모듈 목록 조회
	 * @param request
	 * @param response
	 * @throws Exception
	 */
	@SuppressWarnings("unchecked")
	public JSONObject selectTbbsModlInfCommonList(ParameterMap parameterMap) throws Exception {
		List<Object> dataList = getSqlSession().selectList("TbbsModlInf.selectTbbsModlInfCommonList", parameterMap);
		List<Map<String,Object>> mapList = BeanUtil.convertObjectToMapList(dataList);
		JSONObject json = new JSONObject();
		json.put("boardModuleList", mapList);
		return json;
	}

	/**
	 * 일반 컨텐츠
	 * BOARD TYPE1/TYPE2 : 게시판 모듈 목록 조회
	 * @param request
	 * @param response
	 * @throws Exception
	 */
	@SuppressWarnings("unchecked")
	public JSONObject selectTbbsModlInfTypeList(ParameterMap parameterMap) throws Exception {
		List<Object> dataList = getSqlSession().selectList("TbbsModlInf.selectTbbsModlInfTypeList", parameterMap);
		List<Map<String,Object>> mapList = BeanUtil.convertObjectToMapList(dataList);
		JSONObject json = new JSONObject();
		json.put("boardList", mapList);
		return json;
	}

	/**
	 * 인트라넷 : 게시판 모듈 목록 조회
	 * @param request
	 * @param response
	 * @throws Exception
	 */
	@SuppressWarnings("unchecked")
	public JSONObject selectTbbsModlInfIntraList(ParameterMap parameterMap) throws Exception {
		List<Object> dataList = getSqlSession().selectList("TbbsModlInf.selectTbbsModlInfIntraList", parameterMap);
		List<Map<String,Object>> mapList = BeanUtil.convertObjectToMapList(dataList);
		JSONObject json = new JSONObject();
		json.put("intraModuleList", mapList);
		return json;
	}

	/**
	 * 모듈리스트 조회 (모듈관리)
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public JSONObject selectTbbsModlInfList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TbbsModlInf.selectTbbsModlInfList", parameterMap);
	}
	
	/**
	 * 엑셀다운로드
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public JSONObject excelTbbsModlInfList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TbbsModlInf.excelTbbsModlInfList", parameterMap);
	} 
	
	/**
	 * 모듈 정보 삭제
	 *
	 *
	 */
	public int deleteTbbsModlInf(TbbsModlInf tbbsModlInf) throws Exception {
		return getSqlSession().delete("TbbsModlInf.deleteTbbsModlInf", tbbsModlInf);
	}
	
	public JSONObject getPbbs1001SitSeq(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TbbsModlInf.getPbbs1001SitSeq", parameterMap);
	}
	
	/**
	 * 공지사항 탭 목록 조회
	 * @param  parameterMap
	 * @return List<TbbsModlInf>
	 * @throws Exception
	 */
	public List<TbbsModlInf> selectNotiTabList(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("TbbsModlInf.selectNotiTabList", parameterMap);
	}
	
}