package kr.co.ta9.pandora3.pbbs.dao;

import kr.co.ta9.pandora3.pbbs.dao.base.BaseTbbsDocUsrRtnnDaoTrx;

import org.springframework.stereotype.Repository;

/**
 * TbbsDocUsrRtnnDaoTrx - Transactional DAO(Data Access Object) class for table
 * [TBBS_DOC_USR_RTNN].
 *
 * <pre>
 *  Generated by CodeProcessor. You can freely modify this generated file.
 *  Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TbbsDocUsrRtnnDaoTrx extends BaseTbbsDocUsrRtnnDaoTrx {

}