package kr.co.ta9.pandora3.pbbs.dao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pbbs.dao.base.BaseTbbsQaCmtInfDao;
import kr.co.ta9.pandora3.pcommon.dto.TbbsQaCmtInf;

/**
 * TbbsQaCmtInfDao - DAO(Data Access Object) class for table [TBBS_QA_CMT_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TbbsQaCmtInfDao extends BaseTbbsQaCmtInfDao {
	/**
	 * BOARD TYPE3 : 질문답변형 게시판 답글 목록 조회(그리드형)
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public JSONObject selectTbbsQaCmtInfGridList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TbbsQaCmtInf.selectTbbsQaCmtInfGridList", parameterMap);
	}

	/**
	 * BOARD TYPE3 : 질문답변형 게시판 답글 조회(단건)
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public TbbsQaCmtInf selectTbbsQaCmtInfInfo(ParameterMap parameterMap) {
		return getSqlSession().selectOne("TbbsQaCmtInf.selectTbbsQaCmtInfInfo", parameterMap);
	}
}