package kr.co.ta9.pandora3.pbbs.dao;

import kr.co.ta9.pandora3.pbbs.dao.base.BaseTbbsQaCmtInfDaoTrx;
import kr.co.ta9.pandora3.pcommon.dto.TbbsQaCmtInf;

import org.springframework.stereotype.Repository;

/**
 * TbbsQaCmtInfDaoTrx - Transactional DAO(Data Access Object) class for table
 * [TBBS_QA_CMT_INF].
 *
 * <pre>
 *  Generated by CodeProcessor. You can freely modify this generated file.
 *  Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TbbsQaCmtInfDaoTrx extends BaseTbbsQaCmtInfDaoTrx {


	/*
	 * insertQaCmtInf
	 */
	/**
	 * @param tbbsQaCmtInf TbbsQaCmtInf
	 * @throws Exception
	 */
	public  int insertQaCmtInf(TbbsQaCmtInf tbbsQaCmtInf) throws Exception {
		return getSqlSession().insert("TbbsQaCmtInfTrx.insertQaCmtInf", tbbsQaCmtInf);
	}


}