package kr.co.ta9.pandora3.pbbs.dao;

import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pbbs.dao.base.BaseTmbrPtnrInfDao;
import kr.co.ta9.pandora3.pcommon.dto.TmbrPtnrInf;

import java.util.List;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

/**
 * TmbrPtnrInfDao - DAO(Data Access Object) class for table [TMBR_PTNR_INF].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TmbrPtnrInfDao extends BaseTmbrPtnrInfDao {
	
	/**
	 * WORK 리스트 조회(Paging)
	 * @param  parameterMap
	 * @return JSONObject
	 * @throws Exception
	 */
	public JSONObject selectTmbrPtnrInfGridList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TmbrPtnrInf.selectTmbrPtnrInfGridList", parameterMap);
	}
	
	/**
	 * WORK 상세 조회
	 * @param  parameterMap
	 * @return TmbrPtnrInf
	 * @throws Exception
	 */
	public TmbrPtnrInf selectTmbrPtnrInf(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectOne("TmbrPtnrInf.selectTmbrPtnrInf", parameterMap);
	}
	
	/**
	 * (FRONT) WORK 목록 조회
	 * @return List<TmbrPtnrInf>
	 * @throws Exception
	 */
	public List<TmbrPtnrInf> selectTmbrPtnrInfList() throws Exception {
		return getSqlSession().selectList("TmbrPtnrInf.selectTmbrPtnrInfList");
	}
	
	/**
	 * (FRONT) WORK 년도 목록 조회
	 * @return List<TmbrPtnrInf>
	 * @throws Exception
	 */
	public List<TmbrPtnrInf> selectTmbrPtnrInfYearList() throws Exception {
		return getSqlSession().selectList("TmbrPtnrInf.selectTmbrPtnrInfYearList");
	}

	/**
	 * WORK 리스트 조회 (최근 9건)
	 * @param parameterMap
	 * @return String
	 * @throws Exception
	 */	
	public List<TmbrPtnrInf> selectTmbrPtnrInfMainList() throws Exception {
		return getSqlSession().selectList("TmbrPtnrInf.selectTmbrPtnrInfMainList");
	}	


}