package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTsysUsrRolRtnn;

/**
 * TsysUsrRolRtnn - ValueObject Extended class for table [TSYS_USR_ROL_RTNN].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TsysUsrRolRtnn extends BaseTsysUsrRolRtnn {
	
	private String pw_upd_tr;
	
	private String rol_nm;                 //권한 이름  
	private String usr_nm;                 // 사용자 이름;
    private String bdp_rol;                // bdp 사이트 권한
    private String ams_rol;                // ams 사이트 권한
    private String vip_rol;                // vip 사이트 권한
    private String trd_rol;                // trd 사이트 권한
    private String mlo_rol;                // mlo 사이트 권한
    private String bpn_rol;                // bpn 사이트 권한
    private String cms_rol;                // cms 사이트 권한
    private String bi_rol;                 // bi  사이트 권한
    private String rol_ids;            // 그룹 권한 패핑 권한들
    private String org_cd;
    private String org_nm;
    private String sys_cd;                //사이트번호
    private String sys_nm;                 //사이트명
    private String app_rol_id;             //신청 권한 아이디
    private String f_apvl_dttm;
    private String mstr_cd;
    private String mstr_nm;
    private String cstr_cd;
    private String cstr_nm;
    private String app_dttm;
    private String appl_rsn_cont;
    
	public String getApp_dttm() {
		return app_dttm;
	}

	public void setApp_dttm(String app_dttm) {
		this.app_dttm = app_dttm;
	}

	public String getAppl_rsn_cont() {
		return appl_rsn_cont;
	}

	public void setAppl_rsn_cont(String appl_rsn_cont) {
		this.appl_rsn_cont = appl_rsn_cont;
	}

	public String getMstr_cd() {
		return mstr_cd;
	}

	public void setMstr_cd(String mstr_cd) {
		this.mstr_cd = mstr_cd;
	}

	public String getMstr_nm() {
		return mstr_nm;
	}

	public void setMstr_nm(String mstr_nm) {
		this.mstr_nm = mstr_nm;
	}

	public String getCstr_cd() {
		return cstr_cd;
	}

	public void setCstr_cd(String cstr_cd) {
		this.cstr_cd = cstr_cd;
	}

	public String getCstr_nm() {
		return cstr_nm;
	}

	public void setCstr_nm(String cstr_nm) {
		this.cstr_nm = cstr_nm;
	}

	public String getF_apvl_dttm() {
		return f_apvl_dttm;
	}

	public void setF_apvl_dttm(String f_apvl_dttm) {
		this.f_apvl_dttm = f_apvl_dttm;
	}

	public String getHr_org_nm() {
		return org_nm;
	}

	public void setHr_org_nm(String org_nm) {
		this.org_nm = org_nm;
	}

	public String getApp_rol_id() {
		return app_rol_id;
	}

	public void setApp_rol_id(String app_rol_id) {
		this.app_rol_id = app_rol_id;
	}


	public String getSys_cd() {
		return sys_cd;
	}

	public void setSys_cd(String sys_cd) {
		this.sys_cd = sys_cd;
	}

	public String getSys_nm() {
		return sys_nm;
	}

	public void setSys_nm(String sys_nm) {
		this.sys_nm = sys_nm;
	}

	public String getHr_org_cd() {
		return org_cd;
	}

	public void setHr_org_cd(String org_cd) {
		this.org_cd = org_cd;
	}

	public String getUsr_nm() {
		return usr_nm;
	}

	public void setUsr_nm(String usr_nm) {
		this.usr_nm = usr_nm;
	}

	public String getRol_nm() {
		return rol_nm;
	}

	public void setRol_nm(String rol_nm) {
		this.rol_nm = rol_nm;
	}

	public String getBdp_rol() {
		return bdp_rol;
	}

	public void setBdp_rol(String bdp_rol) {
		this.bdp_rol = bdp_rol;
	}

	public String getAms_rol() {
		return ams_rol;
	}

	public void setAms_rol(String ams_rol) {
		this.ams_rol = ams_rol;
	}

	public String getVip_rol() {
		return vip_rol;
	}

	public void setVip_rol(String vip_rol) {
		this.vip_rol = vip_rol;
	}

	public String getTrd_rol() {
		return trd_rol;
	}

	public void setTrd_rol(String trd_rol) {
		this.trd_rol = trd_rol;
	}

	public String getMlo_rol() {
		return mlo_rol;
	}

	public void setMlo_rol(String mlo_rol) {
		this.mlo_rol = mlo_rol;
	}

	public String getBpn_rol() {
		return bpn_rol;
	}

	public void setBpn_rol(String bpn_rol) {
		this.bpn_rol = bpn_rol;
	}

	public String getCms_rol() {
		return cms_rol;
	}

	public void setCms_rol(String cms_rol) {
		this.cms_rol = cms_rol;
	}

	public String getBi_rol() {
		return bi_rol;
	}

	public void setBi_rol(String bi_rol) {
		this.bi_rol = bi_rol;
	}

	public String getRol_ids() {
		return rol_ids;
	}

	public void setRol_ids(String rol_ids) {
		this.rol_ids = rol_ids;
	}

	public String getPw_upd_tr() {
		return pw_upd_tr;
	}

	public void setPw_upd_tr(String pw_upd_tr) {
		this.pw_upd_tr = pw_upd_tr;
	}
	
}