package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbBcpcAthrApp;

/**
 * TbBcpcAthrApp - ValueObject Extended class for table [TB_BCPC_ATHR_APP].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 05
 */
public class TbBcpcAthrApp extends BaseTbBcpcAthrApp {

	private String rol_ids;                      // 신청 권한들
	private String rol_nms;                      // 권한 이름들
	private String usr_nm;                       // 사용자 이름
	private String apvl_usr_nm;                  // 승인자명
	private String org_nm;                    // 조직 권한명
	private String appl_stat_nm;
	private String sys_cd;
	private String sys_nm;
	private String f_apvl_dttm;
	private String mstr_nm;
	private String cstr_nm;
	private String pos_nm;
	private String app_rol_nm;
		
	
	
	public String getApp_rol_nm() {
		return app_rol_nm;
	}
	public void setApp_rol_nm(String app_rol_nm) {
		this.app_rol_nm = app_rol_nm;
	}
	public String getMstr_nm() {
		return mstr_nm;
	}
	public void setMstr_nm(String mstr_nm) {
		this.mstr_nm = mstr_nm;
	}
	public String getCstr_nm() {
		return cstr_nm;
	}
	public void setCstr_nm(String cstr_nm) {
		this.cstr_nm = cstr_nm;
	}
	public String getHr_emp_pos_nm() {
		return pos_nm;
	}
	public void setHr_emp_pos_nm(String pos_nm) {
		this.pos_nm = pos_nm;
	}
	public String getRol_nms() {
		return rol_nms;
	}
	public void setRol_nms(String rol_nms) {
		this.rol_nms = rol_nms;
	}
	public String getF_apvl_dttm() {
		return f_apvl_dttm;
	}
	public void setF_apvl_dttm(String f_apvl_dttm) {
		this.f_apvl_dttm = f_apvl_dttm;
	}
	public String getAppl_stat_nm() {
		return appl_stat_nm;
	}
	public void setAppl_stat_nm(String appl_stat_nm) {
		this.appl_stat_nm = appl_stat_nm;
	}
	public String getHr_org_nm() {
		return org_nm;
	}
	public void setHr_org_nm(String org_nm) {
		this.org_nm = org_nm;
	}
	public String getApvl_usr_nm() {
		return apvl_usr_nm;
	}
	public void setApvl_usr_nm(String apvl_usr_nm) {
		this.apvl_usr_nm = apvl_usr_nm;
	}
	public String getRol_ids() {
		return rol_ids;
	}
	public void setRol_ids(String rol_ids) {
		this.rol_ids = rol_ids;
	}
	public String getUsr_nm() {
		return usr_nm;
	}
	public void setUsr_nm(String usr_nm) {
		this.usr_nm = usr_nm;
	}
	public String getSys_cd() {
		return sys_cd;
	}
	public void setSys_cd(String sys_cd) {
		this.sys_cd = sys_cd;
	}
	public String getSys_nm() {
		return sys_nm;
	}
	public void setSys_nm(String sys_nm) {
		this.sys_nm = sys_nm;
	}
	
	
}