package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbbsDocUsrRtnn;

/**
 * TbbsDocUsrRtnn - ValueObject Extended class for table [TBBS_DOC_USR_RTNN].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TbbsDocUsrRtnn extends BaseTbbsDocUsrRtnn {

}