package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbbsWbznDspMst;

/**
 * TbbsWbznDspMst - ValueObject Extended class for table [TBBS_WBZN_DSP_MST].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TbbsWbznDspMst extends BaseTbbsWbznDspMst {
	private String ctg_all;
	private String f_crt_dttm;
	private String c_lgn_id;
	private String f_upd_dttm;
	private String u_lgn_id;
	private String chg_pdf_nm;
	private String thumb_nm;
	
	public String getCtg_all() {
		return ctg_all;
	}
	public void setCtg_all(String ctg_all) {
		this.ctg_all = ctg_all;
	}
	public String getF_crt_dttm() {
		return f_crt_dttm;
	}
	public void setF_crt_dttm(String f_crt_dttm) {
		this.f_crt_dttm = f_crt_dttm;
	}
	public String getC_lgn_id() {
		return c_lgn_id;
	}
	public void setC_lgn_id(String c_lgn_id) {
		this.c_lgn_id = c_lgn_id;
	}
	public String getF_upd_dttm() {
		return f_upd_dttm;
	}
	public void setF_upd_dttm(String f_upd_dttm) {
		this.f_upd_dttm = f_upd_dttm;
	}
	public String getU_lgn_id() {
		return u_lgn_id;
	}
	public void setU_lgn_id(String u_lgn_id) {
		this.u_lgn_id = u_lgn_id;
	}
	public String getChg_pdf_nm() {
		return chg_pdf_nm;
	}
	public void setChg_pdf_nm(String chg_pdf_nm) {
		this.chg_pdf_nm = chg_pdf_nm;
	}
	public String getThumb_nm() {
		return thumb_nm;
	}
	public void setThumb_nm(String thumb_nm) {
		this.thumb_nm = thumb_nm;
	}
}
