package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.common.bean.BaseBean;

/**
 * TbBchrEmpI - ValueObject Extended class for table [TB_BCHR_EMP_I].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 08
 */
public class TbDmcuMmcustvocF extends BaseBean {

	private String str_nm;
	private String std_ym;
	private String ques_tp_nm;
	private String ques_tp_cd;
	private int voc01_cnt;
	private int voc02_cnt;
	private int voc03_cnt;
	private int voc04_cnt;
	private int voc_total_cnt;
	
	public String getStr_nm() {
		return str_nm;
	}
	public void setStr_nm(String str_nm) {
		this.str_nm = str_nm;
	}
	public String getStd_ym() {
		return std_ym;
	}
	public void setStd_ym(String std_ym) {
		this.std_ym = std_ym;
	}
	public String getQues_tp_nm() {
		return ques_tp_nm;
	}
	public void setQues_tp_nm(String ques_tp_nm) {
		this.ques_tp_nm = ques_tp_nm;
	}
	public String getQues_tp_cd() {
		return ques_tp_cd;
	}
	public void setQues_tp_cd(String ques_tp_cd) {
		this.ques_tp_cd = ques_tp_cd;
	}
	public int getVoc01_cnt() {
		return voc01_cnt;
	}
	public void setVoc01_cnt(int voc01_cnt) {
		this.voc01_cnt = voc01_cnt;
	}
	public int getVoc02_cnt() {
		return voc02_cnt;
	}
	public void setVoc02_cnt(int voc02_cnt) {
		this.voc02_cnt = voc02_cnt;
	}
	public int getVoc03_cnt() {
		return voc03_cnt;
	}
	public void setVoc03_cnt(int voc03_cnt) {
		this.voc03_cnt = voc03_cnt;
	}
	public int getVoc04_cnt() {
		return voc04_cnt;
	}
	public void setVoc04_cnt(int voc04_cnt) {
		this.voc04_cnt = voc04_cnt;
	}
	public int getVoc_total_cnt() {
		return voc_total_cnt;
	}
	public void setVoc_total_cnt(int voc_total_cnt) {
		this.voc_total_cnt = voc_total_cnt;
	}
	
}