package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.common.bean.BaseBean;

/**
 * TbBchrEmpI - ValueObject Extended class for table [TB_BCHR_EMP_I].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 08
 */
public class TbDmcmMktgrcmcgrpsmryF extends BaseBean {

    private int mktg_psbl_cust_cnt; //마케팅가능고객
    private int pch_fore_cust_cnt; //구매예상고객
    private int chrn_fore_cust_cnt; //이탈위험고객
    private int chrn_rcov_fore_cust_cnt; //이탈회복예상고객
    private int chnl_crs_fore_cust_cnt; //채널확대예상고객
    private int excll_entr_cust_cnt; //우수진입예상고객
    
    
	public int getMktg_psbl_cust_cnt() {
		return mktg_psbl_cust_cnt;
	}
	public void setMktg_psbl_cust_cnt(int mktg_psbl_cust_cnt) {
		this.mktg_psbl_cust_cnt = mktg_psbl_cust_cnt;
	}
	public int getPch_fore_cust_cnt() {
		return pch_fore_cust_cnt;
	}
	public void setPch_fore_cust_cnt(int pch_fore_cust_cnt) {
		this.pch_fore_cust_cnt = pch_fore_cust_cnt;
	}
	public int getChrn_fore_cust_cnt() {
		return chrn_fore_cust_cnt;
	}
	public void setChrn_fore_cust_cnt(int chrn_fore_cust_cnt) {
		this.chrn_fore_cust_cnt = chrn_fore_cust_cnt;
	}
	public int getChrn_rcov_fore_cust_cnt() {
		return chrn_rcov_fore_cust_cnt;
	}
	public void setChrn_rcov_fore_cust_cnt(int chrn_rcov_fore_cust_cnt) {
		this.chrn_rcov_fore_cust_cnt = chrn_rcov_fore_cust_cnt;
	}
	public int getChnl_crs_fore_cust_cnt() {
		return chnl_crs_fore_cust_cnt;
	}
	public void setChnl_crs_fore_cust_cnt(int chnl_crs_fore_cust_cnt) {
		this.chnl_crs_fore_cust_cnt = chnl_crs_fore_cust_cnt;
	}
	public int getExcll_entr_cust_cnt() {
		return excll_entr_cust_cnt;
	}
	public void setExcll_entr_cust_cnt(int excll_entr_cust_cnt) {
		this.excll_entr_cust_cnt = excll_entr_cust_cnt;
	}
    
	
}