package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbLgapMnurolrtnnH;

/**
 * TbLgapMnurolrtnnH - ValueObject Extended class for table [TB_LGAP_MNUROLRTNN_H].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 12. 02
 */
public class TbLgapMnurolrtnnH extends BaseTbLgapMnurolrtnnH {

}