package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbLgapGrprolrtnnH;

/**
 * TbLgapGrprolrtnnH - ValueObject Extended class for table [TB_LGAP_GRPROLRTNN_H].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 28
 */
public class TbLgapGrprolrtnnH extends BaseTbLgapGrprolrtnnH {

}