package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbLgapPgminfH;

/**
 * TbLgapPgminfH - ValueObject Extended class for table [tb_lgap_pgminf_h].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 01. 13
 */
public class TbLgapPgminfH extends BaseTbLgapPgminfH {
	
	private String sys_nm;
	
	public String getSys_nm() {
		return sys_nm;
	}
	public void setSys_nm(String sys_nm) {
		this.sys_nm = sys_nm;
	}

}