package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbPdrCmpnyStafdutyD;

/**
 * TbPdrCmpnyStafdutyD - ValueObject Extended class for table [TB_PDR_CMPNY_STAFDUTY_D].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 05. 21
 */
public class TbPdrCmpnyStafdutyD extends BaseTbPdrCmpnyStafdutyD {

	private String crtr_id;
	private String content_cd;
	private String content_nm;
	private String content_rmk;
	
	public String getCrtr_id() {
		return crtr_id;
	}

	public void setCrtr_id(String crtr_id) {
		this.crtr_id = crtr_id;
	}

	String getContent_cd() {
		return content_cd;
	}

	void setContent_cd(String content_cd) {
		this.content_cd = content_cd;
	}

	String getContent_nm() {
		return content_nm;
	}

	void setContent_nm(String content_nm) {
		this.content_nm = content_nm;
	}

	String getContent_rmk() {
		return content_rmk;
	}

	void setContent_rmk(String content_rmk) {
		this.content_rmk = content_rmk;
	}
}