package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbPdrStafCarrH;

/**
 * TbPdrStafCarrH - ValueObject Extended class for table [TB_PDR_STAF_CARR_H].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 05. 21
 */
public class TbPdrStafCarrH extends BaseTbPdrStafCarrH {

}