package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbPdrStafHrAppntH;

/**
 * TbPdrStafHrAppntH - ValueObject Extended class for table [TB_PDR_STAF_HR_APPNT_H].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 05. 21
 */
public class TbPdrStafHrAppntH extends BaseTbPdrStafHrAppntH {

	private String crtr_id;

	public String getCrtr_id() {
		return crtr_id;
	}

	public void setCrtr_id(String crtr_id) {
		this.crtr_id = crtr_id;
	}	
	
}