package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbPdrStafM;

/**
 * TbPdrStafM - ValueObject Extended class for table [TB_PDR_STAF_M].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 05. 21
 */
public class TbPdrStafM extends BaseTbPdrStafM {

	private String newempno;
	private String crtr_id;
	private String staflevel_nm;
	private String stafjob_nm;
	private String stafduty_nm;
	private String tech_grd_nm;
	private String ho_stat_nm;
	private String cd;
	private String nm;
	private String search;
	
	public String getNewempno() {
		return newempno;
	}

	public void setNewempno(String newempno) {
		this.newempno = newempno;
	}

	public String getCrtr_id() {
		return crtr_id;
	}

	public void setCrtr_id(String crtr_id) {
		this.crtr_id = crtr_id;
	}

	public String getStaflevel_nm() {
		return staflevel_nm;
	}

	public void setStaflevel_nm(String staflevel_nm) {
		this.staflevel_nm = staflevel_nm;
	}

	public String getStafjob_nm() {
		return stafjob_nm;
	}

	public void setStafjob_nm(String stafjob_nm) {
		this.stafjob_nm = stafjob_nm;
	}

	public String getStafduty_nm() {
		return stafduty_nm;
	}

	public void setStafduty_nm(String stafduty_nm) {
		this.stafduty_nm = stafduty_nm;
	}

	public String getTech_grd_nm() {
		return tech_grd_nm;
	}

	public void setTech_grd_nm(String tech_grd_nm) {
		this.tech_grd_nm = tech_grd_nm;
	}

	public String getHo_stat_nm() {
		return ho_stat_nm;
	}

	public void setHo_stat_nm(String ho_stat_nm) {
		this.ho_stat_nm = ho_stat_nm;
	}

	public String getCd() {
		return cd;
	}

	public void setCd(String cd) {
		this.cd = cd;
	}

	public String getNm() {
		return nm;
	}

	public void setNm(String nm) {
		this.nm = nm;
	}

	public String getSearch() {
		return search;
	}

	public void setSearch(String search) {
		this.search = search;
	}

}