package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTmbrAdmLgnInf;

/**
 * TmbrAdmLgnInf - ValueObject Extended class for table [TMBR_ADM_LGN_INF].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TmbrAdmLgnInf extends BaseTmbrAdmLgnInf {
	
	private String f_crt_dttm;
	private String f_upd_dttm;
	private String pw_chg;		// 패스워드 변경 값(암호화 값)
	private String rol_id;
	private String rol_nm;
	private String apl_st_dt;
	private String apl_end_dt;
	private String usr_stat_nm;
	private String pw_upd_tr;
	private String org_nm;
	private String pos_nm;
	private String mngr_tp_nm;
	private String grp_rol_id;
	private String grp_rol_nm;
    private String appl_no;
    private String appl_rsn_cont;
    private String sys_nm;
	private String sys_cls_cd;
	private String excv_yn;
	private String lgn_access_dy;
	private String job_cd;			//직무코드
	private String usr_cl_nm;
	private String sys_cd;
	private String f_pwd_fail_dttm;
	private String f_pwd_upd_dttm;
	
	public String getF_pwd_upd_dttm() {
		return f_pwd_upd_dttm;
	}
	public void setF_pwd_upd_dttm(String f_pwd_upd_dttm) {
		this.f_pwd_upd_dttm = f_pwd_upd_dttm;
	}
	public String getF_pwd_fail_dttm() {
		return f_pwd_fail_dttm;
	}
	public void setF_pwd_fail_dttm(String f_pwd_fail_dttm) {
		this.f_pwd_fail_dttm = f_pwd_fail_dttm;
	}
	public String getF_crt_dttm() {
		return f_crt_dttm;
	}
	public void setF_crt_dttm(String f_crt_dttm) {
		this.f_crt_dttm = f_crt_dttm;
	}
	public String getF_upd_dttm() {
		return f_upd_dttm;
	}
	public void setF_upd_dttm(String f_upd_dttm) {
		this.f_upd_dttm = f_upd_dttm;
	}
	public String getPw_chg() {
		return pw_chg;
	}
	public void setPw_chg(String pw_chg) {
		this.pw_chg = pw_chg;
	}
	public String getRol_id() {
		return rol_id;
	}
	public void setRol_id(String rol_id) {
		this.rol_id = rol_id;
	}
	public String getRol_nm() {
		return rol_nm;
	}
	public void setRol_nm(String rol_nm) {
		this.rol_nm = rol_nm;
	}
	public String getApl_st_dt() {
		return apl_st_dt;
	}
	public void setApl_st_dt(String apl_st_dt) {
		this.apl_st_dt = apl_st_dt;
	}
	public String getApl_end_dt() {
		return apl_end_dt;
	}
	public void setApl_end_dt(String apl_end_dt) {
		this.apl_end_dt = apl_end_dt;
	}
	public String getUsr_stat_nm() {
		return usr_stat_nm;
	}
	public void setUsr_stat_nm(String usr_stat_nm) {
		this.usr_stat_nm = usr_stat_nm;
	}
	public String getPw_upd_tr() {
		return pw_upd_tr;
	}
	public void setPw_upd_tr(String pw_upd_tr) {
		this.pw_upd_tr = pw_upd_tr;
	}
	public String getOrg_nm() {
		return org_nm;
	}
	public void setOrg_nm(String org_nm) {
		this.org_nm = org_nm;
	}
	public String getPos_nm() {
		return pos_nm;
	}
	public void setPos_nm(String pos_nm) {
		this.pos_nm = pos_nm;
	}
	public String getMngr_tp_nm() {
		return mngr_tp_nm;
	}
	public void setMngr_tp_nm(String mngr_tp_nm) {
		this.mngr_tp_nm = mngr_tp_nm;
	}
	public String getGrp_rol_id() {
		return grp_rol_id;
	}
	public void setGrp_rol_id(String grp_rol_id) {
		this.grp_rol_id = grp_rol_id;
	}
	public String getGrp_rol_nm() {
		return grp_rol_nm;
	}
	public void setGrp_rol_nm(String grp_rol_nm) {
		this.grp_rol_nm = grp_rol_nm;
	}
	public String getAppl_no() {
		return appl_no;
	}
	public void setAppl_no(String appl_no) {
		this.appl_no = appl_no;
	}
	public String getAppl_rsn_cont() {
		return appl_rsn_cont;
	}
	public void setAppl_rsn_cont(String appl_rsn_cont) {
		this.appl_rsn_cont = appl_rsn_cont;
	}
	
	
	public String getSys_nm() {
		return sys_nm;
	}
	public void setSys_nm(String sys_nm) {
		this.sys_nm = sys_nm;
	}
	public String getSys_cls_cd() {
		return sys_cls_cd;
	}
	public void setSys_cls_cd(String sys_cls_cd) {
		this.sys_cls_cd = sys_cls_cd;
	}
	public String getExcv_yn() {
		return excv_yn;
	}
	public void setExcv_yn(String excv_yn) {
		this.excv_yn = excv_yn;
	}
	public String getLgn_access_dy() {
		return lgn_access_dy;
	}
	public void setLgn_access_dy(String lgn_access_dy) {
		this.lgn_access_dy = lgn_access_dy;
	}
	public String getJob_cd() {
		return job_cd;
	}
	public void setJob_cd(String job_cd) {
		this.job_cd = job_cd;
	}
	public String getUsr_cl_nm() {
		return usr_cl_nm;
	}
	public void setUsr_cl_nm(String usr_cl_nm) {
		this.usr_cl_nm = usr_cl_nm;
	}
	public String getSys_cd() {
		return sys_cd;
	}
	public void setSys_cd(String sys_cd) {
		this.sys_cd = sys_cd;
	}
	
}