package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTmbrCluHst;

/**
 * TmbrCluHst - ValueObject Extended class for table [TMBR_CLU_HST].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TmbrCluHst extends BaseTmbrCluHst {
	private String clu_tp_cd_nm;
	private String clu_cls_cd_nm;
	
	public String getClu_tp_cd_nm() {
		return clu_tp_cd_nm;
	}
	public void setClu_tp_cd_nm(String clu_tp_cd_nm) {
		this.clu_tp_cd_nm = clu_tp_cd_nm;
	}
	public String getClu_cls_cd_nm() {
		return clu_cls_cd_nm;
	}
	public void setClu_cls_cd_nm(String clu_cls_cd_nm) {
		this.clu_cls_cd_nm = clu_cls_cd_nm;
	}
}