package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTmbrAdmLastLgnInf;

/**
 * TmbrAdmLastLgnInf - ValueObject Extended class for table [TMBR_ADM_LAST_LGN_INF].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 13
 */
public class TmbrAdmLastLgnInf extends BaseTmbrAdmLastLgnInf {

}