package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTmbrUsrInf;

/**
 * TmbrUsrInf - ValueObject Extended class for table [TMBR_USR_INF].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TmbrUsrInf extends BaseTmbrUsrInf {
	
	private String f_crt_dttm;
	private String jn_ctf_key_tr;
	private String eml_ctf_key_tr;
	private String pw_upd_tr;
	private String usr_tel_no;
	private String usr_mbl_no;
	private String scsn_dttm;
	
	public String getF_crt_dttm() {
		return f_crt_dttm;
	}
	public void setF_crt_dttm(String f_crt_dttm) {
		this.f_crt_dttm = f_crt_dttm;
	}
	public String getJn_ctf_key_tr() {
		return jn_ctf_key_tr;
	}
	public void setJn_ctf_key_tr(String jn_ctf_key_tr) {
		this.jn_ctf_key_tr = jn_ctf_key_tr;
	}
	public String getEml_ctf_key_tr() {
		return eml_ctf_key_tr;
	}
	public void setEml_ctf_key_tr(String eml_ctf_key_tr) {
		this.eml_ctf_key_tr = eml_ctf_key_tr;
	}
	public String getPw_upd_tr() {
		return pw_upd_tr;
	}
	public void setPw_upd_tr(String pw_upd_tr) {
		this.pw_upd_tr = pw_upd_tr;
	}
	public String getUsr_tel_no() {
		return usr_tel_no;
	}
	public void setUsr_tel_no(String usr_tel_no) {
		this.usr_tel_no = usr_tel_no;
	}
	public String getUsr_mbl_no() {
		return usr_mbl_no;
	}
	public void setUsr_mbl_no(String usr_mbl_no) {
		this.usr_mbl_no = usr_mbl_no;
	}
	public String getScsn_dttm() {
		return scsn_dttm;
	}
	public void setScsn_dttm(String scsn_dttm) {
		this.scsn_dttm = scsn_dttm;
	}
	
}