package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTsysOrgBtnRolRtnn;

/**
 * TsysOrgBtnRolRtnn - ValueObject Extended class for table [TSYS_ORG_BTN_ROL_RTNN].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 03. 13
 */
public class TsysOrgBtnRolRtnn extends BaseTsysOrgBtnRolRtnn {
	private String pgm_btn_nm;

	public String getPgm_btn_nm() {
		return pgm_btn_nm;
	}

	public void setPgm_btn_nm(String pgm_btn_nm) {
		this.pgm_btn_nm = pgm_btn_nm;
	}
	
	

}