package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTsysPgmInf;

/**
 * TsysPgmInf - ValueObject Extended class for table [TSYS_PGM_INF].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TsysPgmInf extends BaseTsysPgmInf {
	private String cd_nm;
	private String ref_1;
	private String sys_nm;
	private String btn_sch;
	private String btn_add;
	private String btn_apv;
	private String btn_sv;
	private String btn_xls;
	private String btn_del;
	private String btn_prn;
	private String btn_hco;
	private String btn_inf;
	private String btn_addRow;
	private String btn_delRow;
	private String btn_new;
	private String btn_xls_download;
	private String btn_xls_upload;
	
	private String pgm_btn_cd;
	
	public String getSys_nm() {
		return sys_nm;
	}
	public void setSys_nm(String sys_nm) {
		this.sys_nm = sys_nm;
	}
	public String getBtn_sch() {
		return btn_sch;
	}
	public void setBtn_sch(String btn_sch) {
		this.btn_sch = btn_sch;
	}
	public String getBtn_add() {
		return btn_add;
	}
	public void setBtn_add(String btn_add) {
		this.btn_add = btn_add;
	}
	public String getBtn_apv() {
		return btn_apv;
	}
	public void setBtn_apv(String btn_apv) {
		this.btn_apv = btn_apv;
	}
	public String getBtn_sv() {
		return btn_sv;
	}
	public void setBtn_sv(String btn_sv) {
		this.btn_sv = btn_sv;
	}
	public String getBtn_xls() {
		return btn_xls;
	}
	public void setBtn_xls(String btn_xls) {
		this.btn_xls = btn_xls;
	}
	public String getBtn_del() {
		return btn_del;
	}
	public void setBtn_del(String btn_del) {
		this.btn_del = btn_del;
	}
	public String getBtn_prn() {
		return btn_prn;
	}
	public void setBtn_prn(String btn_prn) {
		this.btn_prn = btn_prn;
	}
	public String getBtn_hco() {
		return btn_hco;
	}
	public void setBtn_hco(String btn_hco) {
		this.btn_hco = btn_hco;
	}
	public String getBtn_inf() {
		return btn_inf;
	}
	public void setBtn_inf(String btn_inf) {
		this.btn_inf = btn_inf;
	}
	public String getCd_nm() {
		return cd_nm;
	}
	public void setCd_nm(String cd_nm) {
		this.cd_nm = cd_nm;
	}
	public String getRef_1() {
		return ref_1;
	}
	public void setRef_1(String ref_1) {
		this.ref_1 = ref_1;
	}
	public String getPgm_btn_cd() {
		return pgm_btn_cd;
	}
	public void setPgm_btn_cd(String pgm_btn_cd) {
		this.pgm_btn_cd = pgm_btn_cd;
	}
	public String getBtn_addRow() {
		return btn_addRow;
	}
	public void setBtn_addRow(String btn_addRow) {
		this.btn_addRow = btn_addRow;
	}
	public String getBtn_delRow() {
		return btn_delRow;
	}
	public void setBtn_delRow(String btn_delRow) {
		this.btn_delRow = btn_delRow;
	}
	public String getBtn_new() {
		return btn_new;
	}
	public void setBtn_new(String btn_new) {
		this.btn_new = btn_new;
	}
	public String getBtn_xls_download() {
		return btn_xls_download;
	}
	public void setBtn_xls_download(String btn_xls_download) {
		this.btn_xls_download = btn_xls_download;
	}
	public String getBtn_xls_upload() {
		return btn_xls_upload;
	}
	public void setBtn_xls_upload(String btn_xls_upload) {
		this.btn_xls_upload = btn_xls_upload;
	}
	
}