package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTsysAdmOrgGrpRolRtnn;

/**
 * TsysAdmOrgGrpRolRtnn - ValueObject Extended class for table [TSYS_ADM_ORG_GRP_ROL_RTNN].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 10. 29
 */
public class TsysAdmOrgGrpRolRtnn extends BaseTsysAdmOrgGrpRolRtnn {
	
	private String grp_rol_nm;  //권한 그룹 명
	private String org_nm;		//조직 이름
	
	
	public String getGrp_rol_nm() {
		return grp_rol_nm;
	}
	public void setGrp_rol_nm(String grp_rol_nm) {
		this.grp_rol_nm = grp_rol_nm;
	}
	
	public String getHr_org_nm() {
		return org_nm;
	}
	public void setHr_org_nm(String org_nm) {
		this.org_nm = org_nm;
	}
	

}