package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTsysPgmBtnInf;

/**
 * TsysPgmBtnInf - ValueObject Extended class for table [TSYS_PGM_BTN_INF].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TsysPgmBtnInf extends BaseTsysPgmBtnInf {

}