package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTsysUsrRol;

/**
 * TsysUsrRol - ValueObject Extended class for table [TSYS_USR_ROL].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TsysUsrRol extends BaseTsysUsrRol {
	
	private String f_upd_dttm;
	private String rol_yn;
	private String f_apl_st_dt;
	private String f_apl_ed_dt;
	
	public String getF_upd_dttm() {
		return f_upd_dttm;
	}
	public void setF_upd_dttm(String f_upd_dttm) {
		this.f_upd_dttm = f_upd_dttm;
	}
	public String getRol_yn() {
		return rol_yn;
	}
	public void setRol_yn(String rol_yn) {
		this.rol_yn = rol_yn;
	}
	public String getF_apl_st_dt() {
		return f_apl_st_dt;
	}
	public void setF_apl_st_dt(String f_apl_st_dt) {
		this.f_apl_st_dt = f_apl_st_dt;
	}
	public String getF_apl_ed_dt() {
		return f_apl_ed_dt;
	}
	public void setF_apl_ed_dt(String f_apl_ed_dt) {
		this.f_apl_ed_dt = f_apl_ed_dt;
	}
	
}
