package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTsysOrg;

/**
 * TsysOrg - ValueObject Extended class for table [TSYS_ORG].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 03. 14
 */
public class TsysOrg extends BaseTsysOrg {

	//상위 조직 이름
	private String up_org_nm;

	public String getUp_org_nm() {
		return up_org_nm;
	}

	public void setUp_org_nm(String up_org_nm) {
		this.up_org_nm = up_org_nm;
	}

	
}