package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTsysOrgRolRtnn;

/**
 * TsysOrgRolRtnn - ValueObject Extended class for table [TSYS_ORG_ROL_RTNN].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 03. 22
 */
public class TsysOrgRolRtnn extends BaseTsysOrgRolRtnn
{

}