package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.common.bean.BaseBean;

/**
 * TbBchrEmpI - ValueObject Extended class for table [TB_BCHR_EMP_I].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 08
 */
public class TbDicmsTsttscuststyF extends BaseBean {

	private int sty_cust_cnt;
	private int prk_cust_cnt;
	private int pch_cust_cnt;
	private int poc_cust_cnt;
	private int lnge_cust_cnt;
	private String load_dttm;
	private String msg_name;
	
	
	
	public String getMsg_name() {
		return msg_name;
	}
	public void setMsg_name(String msg_name) {
		this.msg_name = msg_name;
	}
	public int getSty_cust_cnt() {
		return sty_cust_cnt;
	}
	public void setSty_cust_cnt(int sty_cust_cnt) {
		this.sty_cust_cnt = sty_cust_cnt;
	}
	public int getPrk_cust_cnt() {
		return prk_cust_cnt;
	}
	public void setPrk_cust_cnt(int prk_cust_cnt) {
		this.prk_cust_cnt = prk_cust_cnt;
	}
	public int getPch_cust_cnt() {
		return pch_cust_cnt;
	}
	public void setPch_cust_cnt(int pch_cust_cnt) {
		this.pch_cust_cnt = pch_cust_cnt;
	}
	public int getPoc_cust_cnt() {
		return poc_cust_cnt;
	}
	public void setPoc_cust_cnt(int poc_cust_cnt) {
		this.poc_cust_cnt = poc_cust_cnt;
	}
	public int getLnge_cust_cnt() {
		return lnge_cust_cnt;
	}
	public void setLnge_cust_cnt(int lnge_cust_cnt) {
		this.lnge_cust_cnt = lnge_cust_cnt;
	}
	public String getLoad_dttm() {
		return load_dttm;
	}
	public void setLoad_dttm(String load_dttm) {
		this.load_dttm = load_dttm;
	}
	
	
}