package kr.co.ta9.pandora3.psys.dao;

import java.util.List;
import java.util.Map;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.dao.CommonDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;

/**
 * TbBcPcHRrshopbuyDao - DAO(Data Access Object) class for table [TB_BCPC_ORGATHR].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 02. 28
 */
@Repository
public class TbBcPcHRrshopbuyDao extends CommonDao {

    /**
     * 조직별권한관리 > 모/자점 목록 조회  (매장조직)
     * @param parameterMap
     * @throws Exception
     */
    public JSONObject selectStrList(ParameterMap parameterMap) throws Exception {
        return queryForGrid("TbBcPcHRrshopbuy.selectStrList", parameterMap);
    }
    /**
     * 조직별권한관리 > 부문목록 조회 (매입조직)
     * @param parameterMap
     * @throws Exception
     */
    public JSONObject selectBuyFldList(ParameterMap parameterMap) throws Exception {
        return queryForGrid("TbBcPcHRrshopbuy.selectBuyFldList", parameterMap);
    }

    /**
     * 조직별권한관리 > 선택 점에 대한 매장층 목록 조회 (매장조직)
     * @param parameterMap
     * @throws Exception
     */
    public List<Map<String, Object>> selectShopFloorList(ParameterMap parameterMap) throws Exception {
        return getSqlSession().selectList("TbBcPcHRrshopbuy.selectShopFloorList", parameterMap);
    }

    /**
     * 조직별권한관리 > 선택 점에 대한 매입팀 목록 조회 (매입조직)
     * @param parameterMap
     * @throws Exception
     */
    public List<Map<String, Object>> selectBuyFloorList(ParameterMap parameterMap) throws Exception {
        return getSqlSession().selectList("TbBcPcHRrshopbuy.selectBuyFloorList", parameterMap);

    }
    /**
     * 조직별권한관리 > 선택 점/층에 대한 매장PC목록 조회  (매장조직)
     * @param parameterMap
     * @throws Exception
     */
    public List<Map<String, Object>> selectShopPcList(ParameterMap parameterMap) throws Exception {
        return getSqlSession().selectList("TbBcPcHRrshopbuy.selectShopPcList", parameterMap);
    }

    /**
     * 조직별권한관리 > 선택 점/층에 대한 매입PC목록 조회  (매입조직)
     * @param parameterMap
     * @throws Exception
     */
    public List<Map<String, Object>> selectBuyPcList(ParameterMap parameterMap) throws Exception {
        return getSqlSession().selectList("TbBcPcHRrshopbuy.selectBuyPcList", parameterMap);
    }

}