package kr.co.ta9.pandora3.pcmn.dao;

import java.util.List;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TcmnCdDtl;

/**
 * TcmnCdDtlDao - DAO(Data Access Object) class for table [TCMN_CD_DTL].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TcmnCdDtlDao extends BaseDao {

	/**
	 * 코드 리스트 조회
	 * @param parameterMap
	 * @return List<SysCdDtl>
	 * @throws Exception
	 */
	public List<TcmnCdDtl> selectTcmnCdDtlList(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("TcmnCdDtl.selectTcmnCdDtlList", parameterMap);
	}

	/**
	 * 코드상세 리스트 조회 (그리드형)
	 * @param parameterMap
	 * @return JSONObject
	 * @throws Exception
	 */
	public JSONObject selectTcmnCdDtlGridList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TcmnCdDtl.selectTcmnCdDtlGridList", parameterMap);
	}

	/**
	 * 키중복 체크
	 * @param parameterMap
	 * @return int
	 * @throws Exception
	 */

	public int selectTcmnCdDtlCnt(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectOne("TcmnCdDtl.selectTcmnCdDtlCnt", parameterMap);
	}

	/**
	 * 코드 리스트 조회(MST_CD 복수)
	 * @param parameterMap
	 * @return List<SysCdDtl>
	 * @throws Exception
	 */
	public List<TcmnCdDtl> selectTcmnCdDtlMultiList(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectList("TcmnCdDtl.selectTcmnCdDtlMultiList", parameterMap);
	}

	/**
	 * CDNM 중복 체크
	 * @param parameterMap
	 * @return int
	 * @throws Exception
	 */
	public int selectTcmnCdDtlCdNm(ParameterMap parameterMap) throws Exception {
		return getSqlSession().selectOne("TcmnCdDtl.selectTcmnCdDtlCdNm", parameterMap);
	}

	public int getTcmnCdDtlCDCnt() throws Exception{
		return getSqlSession().selectOne("TcmnCdDtl.getTcmnCdDtlCDCnt");
	}

	/**
	 * 사이트 적재 로그 관련 조회
	 * @param parameterMap
	 * @return
	 */
	public List<String> selectTcmnCdDtlSitLog() throws Exception {
		return getSqlSession().selectList("TcmnCdDtl.selectTcmnCdDtlSitLog");
	}
	

}