package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbLgapVmsprinfschH;

/**
 * TbLgapVmsprinfschH - ValueObject Extended class for table [TB_LGAP_VMSPRINFSCH_H].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 12. 09
 */
public class TbLgapVmsprinfschH extends BaseTbLgapVmsprinfschH {

}