package kr.co.ta9.pandora3.pwzn.dao;

import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.pwzn.dao.base.BaseTbbsWbznDspMstDaoTrx;

/**
 * TbbsWbznDspMstDaoTrx - Transactional DAO(Data Access Object) class for table
 * [TBBS_WBZN_DSP_MST].
 *
 * <pre>
 *  Generated by CodeProcessor. You can freely modify this generated file.
 *  Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TbbsWbznDspMstDaoTrx extends BaseTbbsWbznDspMstDaoTrx {
	

}