package kr.co.ta9.pandora3.pcommon.dto;

import org.json.simple.JSONObject;

import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbPdrCmpnyUseSysH;

/**
 * TbPdrCmpnyUseSysH - ValueObject Extended class for table [TB_PDR_CMPNY_USE_SYS_H].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 05. 20
 */
public class TbPdrCmpnyUseSysH extends BaseTbPdrCmpnyUseSysH {
	/** crtr_id (CRTR_ID) */
	private String crtr_id;
	
	/** updr_id (UPDR_ID) */
	private String updr_id;
	
	/** prd_nm (PRD_NM) */
	private String prd_nm;	

	public String getCrtr_id() {
		return crtr_id;
	}

	public void setCrtr_id(String crtr_id) {
		this.crtr_id = crtr_id;
	}

	public String getUpdr_id() {
		return updr_id;
	}

	public void setUpdr_id(String updr_id) {
		this.updr_id = updr_id;
	}

	public String getPrd_nm() {
		return prd_nm;
	}

	public void setPrd_nm(String prd_nm) {
		this.prd_nm = prd_nm;
	}

}