package kr.co.ta9.pandora3.psys.dao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TsysUsrRolRtnn;

/**
 * TsysUsrRolRtnnDao - DAO(Data Access Object) class for table [TSYS_USR_ROL_RTNN].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
@Repository
public class TsysUsrRolRtnnDao extends BaseDao {
	
	/**
	 * 사용자 권한 목록 (전체)
	 * @param  parameterMap
	 * @return JSONObject
	 * @throws Exception
	 */
	public JSONObject selectTsysUsrRolRtnnGridList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysUsrRolRtnn.selectTsysUsrRolRtnnGridList", parameterMap);
	}

	/**
	 * 권한신청관리 > 개별 권한 신청 목록 
	 * @param parameterMap
	 * @return JSONObject
	 * @throws Exception
	 */
	public JSONObject selectTsysUsrRolRtnnAppGridList(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TsysUsrRolRtnn.selectTsysUsrRolRtnnAppGridList", parameterMap);
	}
	
	/**
	 * 사용자 권한 할당
	 * @param  tsysUsrRolRtnn
	 * @return int
	 * @throws Exception
	 */
	public int insertTsysUsrRolRtnn(TsysUsrRolRtnn tsysUsrRolRtnn) throws Exception {
		return getSqlSession().insert("TsysUsrRolRtnn.insertTsysUsrRolRtnn", tsysUsrRolRtnn);
	}
	
}