package kr.co.ta9.pandora3.psys.dao;

import org.json.simple.JSONObject;
import org.springframework.stereotype.Repository;

import kr.co.ta9.pandora3.app.repository.BaseDao;
import kr.co.ta9.pandora3.app.servlet.ParameterMap;
import kr.co.ta9.pandora3.pcommon.dto.TbBcpcAthrApp;

/**
 * TbBcpcAthrAppDao - DAO(Data Access Object) class for table [TB_BCPC_ATHR_APP].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 05
 */
@Repository
public class TbBcpcAthrAppDao extends BaseDao {

	/**
	 * 권한관리 > 권한 승인 관리
	 * @param parameterMap
	 */
	public JSONObject selectTbBcpcAtharApp(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TbBcpcAthrApp.selectTbBcpcAtharApp", parameterMap);
	}

	/**
	 * VIP 권한 승인 관리.
	 * @param parameterMap
	 * @return
	 * @throws Exception
	 */
	public JSONObject selectTbBcpcAtharAppVIP(ParameterMap parameterMap) throws Exception {
		return queryForGrid("TbBcpcAthrApp.selectTbBcpcAtharAppVIP", parameterMap);
	}
	
	/**
	 *  개별 권한 신청
	 * @param tbBcpcAthrApp
	 * @return int
	 * @throws Exception
	 */
	public int insertTbBcpcAthrApp(TbBcpcAthrApp tbBcpcAthrApp) throws Exception {
		return getSqlSession().insert("TbBcpcAthrApp.insertTbbcpcAthrApp", tbBcpcAthrApp);
	}

	/**
	 * 개별 권한 신청 승인 관리.
	 * @param tbBcpcAthrApp
	 * @throws Exception
	 */
	public int updateTbBcpcAthrApp(TbBcpcAthrApp tbBcpcAthrApp) throws Exception {
		return getSqlSession().update("TbBcpcAthrApp.updateTbBcpcAthrApp", tbBcpcAthrApp);
	}

}