package kr.co.ta9.pandora3.psys.dao;

import kr.co.ta9.pandora3.psys.dao.base.BaseTbLgapGrprolrtnnHDao;

import org.springframework.stereotype.Repository;

/**
 * TbLgapGrprolrtnnHDao - DAO(Data Access Object) class for table [TB_LGAP_GRPROLRTNN_H].
 *
 * <pre>
 *   Generated by CodeProcessor. You can freely modify this generated file.
 *   Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 28
 */
@Repository
public class TbLgapGrprolrtnnHDao extends BaseTbLgapGrprolrtnnHDao {

}