package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbLgapRolrtnnH;

/**
 * TbLgapRolrtnnH - ValueObject Extended class for table [TB_LGAP_ROLRTNN_H].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 14
 */
public class TbLgapRolrtnnH extends BaseTbLgapRolrtnnH {

}