package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbPdrCmpnyM;

/**
 * TbPdrCmpnyM - ValueObject Extended class for table [TB_PDR_CMPNY_M].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 05. 20
 */
public class TbPdrCmpnyM extends BaseTbPdrCmpnyM {
	/** srch_txt (SRCH_TXT) */
	private String srch_txt;
	/** srch_result_txt (SRCH_RESULT_TXT) */
	private String srch_result_txt;
	/** c_cntrt_sta_dy (CNTRT_STA_DY) */
	private String c_cntrt_sta_dy;	
	/** c_cntrt_end_dy (CNTRT_END_DY) */
	private String c_cntrt_end_dy;	
	/** crtr_id (CRTR_ID) */
	private String crtr_id;
	
	/** updr_id (UPDR_ID) */
	private String updr_id;

	public String getCrtr_id() {
		return crtr_id;
	}

	public void setCrtr_id(String crtr_id) {
		this.crtr_id = crtr_id;
	}

	public String getUpdr_id() {
		return updr_id;
	}

	public void setUpdr_id(String updr_id) {
		this.updr_id = updr_id;
	}
	public String getSrch_txt() {
		return srch_txt;
	}
	public void setSrch_txt(String srch_txt) {
		this.srch_txt = srch_txt;
	}
	public String getSrch_result_txt() {
		return srch_result_txt;
	}
	public void setSrch_result_txt(String srch_result_txt) {
		this.srch_result_txt = srch_result_txt;
	}
	public String getC_cntrt_sta_dy() {
		return c_cntrt_sta_dy;
	}
	public void setC_cntrt_sta_dy(String c_cntrt_sta_dy) {
		this.c_cntrt_sta_dy = c_cntrt_sta_dy;
	}
	public String getC_cntrt_end_dy() {
		return c_cntrt_end_dy;
	}
	public void setC_cntrt_end_dy(String c_cntrt_end_dy) {
		this.c_cntrt_end_dy = c_cntrt_end_dy;
	}	
	
	

}