package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.app.bean.CommonBean;

/**
 * TbBcPcOrgAthr - ValueObject Extended class for table [TB_BCPC_ORGATHR].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2020. 02. 28
 */
public class TbBcPcOrgAthr extends CommonBean {

	private String org_cd;
    private String hr_pos_cd;
    private String hr_pos_nm;
    private String job_cd;
    private String job_nm;
    private String sys_cls_cd;
    private String grp_rol_id;
    private String grp_rol_nm;
    private String shop_grde_cd;
    private String buy_grde_cd;
    private String mstrs_uspr_id;
    private String excv_yn;
    private String cstr_cd;
    private String cstr_nm;
    private String sys_cl_nm;
    private String bi_mstrs_cd;
    private String bi_mstrs_nm;

    public String getHr_org_cd() {
        return org_cd;
    }
    public void setHr_org_cd(String org_cd) {
        this.org_cd = org_cd;
    }
    public String getHr_pos_cd() {
        return hr_pos_cd;
    }
    public void setHr_pos_cd(String hr_pos_cd) {
        this.hr_pos_cd = hr_pos_cd;
    }
    public String getHr_pos_nm() {
        return hr_pos_nm;
    }
    public void setHr_pos_nm(String hr_pos_nm) {
        this.hr_pos_nm = hr_pos_nm;
    }
    public String getJob_cd() {
        return job_cd;
    }
    public void setJob_cd(String job_cd) {
        this.job_cd = job_cd;
    }
    public String getJbfn_nm() {
        return job_nm;
    }
    public void setJbfn_nm(String job_nm) {
        this.job_nm = job_nm;
    }
    public String getSys_cls_cd() {
        return sys_cls_cd;
    }
    public void setSys_cls_cd(String sys_cls_cd) {
        this.sys_cls_cd = sys_cls_cd;
    }
    public String getGrp_rol_id() {
        return grp_rol_id;
    }
    public void setGrp_rol_id(String grp_rol_id) {
        this.grp_rol_id = grp_rol_id;
    }
    public String getGrp_rol_nm() {
        return grp_rol_nm;
    }
    public void setGrp_rol_nm(String grp_rol_nm) {
        this.grp_rol_nm = grp_rol_nm;
    }
    public String getShop_grde_cd() {
        return shop_grde_cd;
    }
    public void setShop_grde_cd(String shop_grde_cd) {
        this.shop_grde_cd = shop_grde_cd;
    }
    public String getBuy_grde_cd() {
        return buy_grde_cd;
    }
    public void setBuy_grde_cd(String buy_grde_cd) {
        this.buy_grde_cd = buy_grde_cd;
    }
    public String getMstrs_uspr_id() {
        return mstrs_uspr_id;
    }
    public void setMstrs_uspr_id(String mstrs_uspr_id) {
        this.mstrs_uspr_id = mstrs_uspr_id;
    }
    public String getExcv_yn() {
        return excv_yn;
    }
    public void setExcv_yn(String excv_yn) {
        this.excv_yn = excv_yn;
    }
    public String getCstr_cd() {
        return cstr_cd;
    }
    public void setCstr_cd(String cstr_cd) {
        this.cstr_cd = cstr_cd;
    }
    public String getCstr_nm() {
        return cstr_nm;
    }
    public void setCstr_nm(String cstr_nm) {
        this.cstr_nm = cstr_nm;
    }
    public String getSys_cl_nm() {
        return sys_cl_nm;
    }
    public void setSys_cl_nm(String sys_cl_nm) {
        this.sys_cl_nm = sys_cl_nm;
    }
    public String getBi_mstrs_cd() {
        return bi_mstrs_cd;
    }
    public void setBi_mstrs_cd(String bi_mstrs_cd) {
        this.bi_mstrs_cd = bi_mstrs_cd;
    }
    public String getBi_mstrs_nm() {
        return bi_mstrs_nm;
    }
    public void setBi_mstrs_nm(String bi_mstrs_nm) {
        this.bi_mstrs_nm = bi_mstrs_nm;
    }

}