package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.common.bean.BaseBean;

/**
 * TbBchrEmpI - ValueObject Extended class for table [TB_BCHR_EMP_I].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 08
 */
public class TbBcpcWthr extends BaseBean {

	private String std_dt;
	private String wthr_tm;
	private String cstr_cd;
	private String cstr_nm;
	private String dayw_abrv_nm;
	private String mcty_cd;
	private String mcty_nm;
	private String sigungu_nm;
	private String sigungu_cd;
	private int now_atmpr;
	private int fl_atmpr;
	private int now_ranfl;
	private String wthr_icon_cd;
	private String wthr_cl_nm;
	private int fn_dst_cnct;
	private int utrfn_dst_cnct;
	
	
	public String getStd_dt() {
		return std_dt;
	}
	public void setStd_dt(String std_dt) {
		this.std_dt = std_dt;
	}
	public String getWthr_tm() {
		return wthr_tm;
	}
	public void setWthr_tm(String wthr_tm) {
		this.wthr_tm = wthr_tm;
	}
	public String getCstr_cd() {
		return cstr_cd;
	}
	public void setCstr_cd(String cstr_cd) {
		this.cstr_cd = cstr_cd;
	}
	public String getCstr_nm() {
		return cstr_nm;
	}
	public void setCstr_nm(String cstr_nm) {
		this.cstr_nm = cstr_nm;
	}
	public String getDayw_abrv_nm() {
		return dayw_abrv_nm;
	}
	public void setDayw_abrv_nm(String dayw_abrv_nm) {
		this.dayw_abrv_nm = dayw_abrv_nm;
	}
	public String getMcty_cd() {
		return mcty_cd;
	}
	public void setMcty_cd(String mcty_cd) {
		this.mcty_cd = mcty_cd;
	}
	public String getMcty_nm() {
		return mcty_nm;
	}
	public void setMcty_nm(String mcty_nm) {
		this.mcty_nm = mcty_nm;
	}
	public String getSigungu_nm() {
		return sigungu_nm;
	}
	public void setSigungu_nm(String sigungu_nm) {
		this.sigungu_nm = sigungu_nm;
	}
	public String getSigungu_cd() {
		return sigungu_cd;
	}
	public void setSigungu_cd(String sigungu_cd) {
		this.sigungu_cd = sigungu_cd;
	}
	public int getNow_atmpr() {
		return now_atmpr;
	}
	public void setNow_atmpr(int now_atmpr) {
		this.now_atmpr = now_atmpr;
	}
	public int getFl_atmpr() {
		return fl_atmpr;
	}
	public void setFl_atmpr(int fl_atmpr) {
		this.fl_atmpr = fl_atmpr;
	}
	public int getNow_ranfl() {
		return now_ranfl;
	}
	public void setNow_ranfl(int now_ranfl) {
		this.now_ranfl = now_ranfl;
	}
	public String getWthr_icon_cd() {
		return wthr_icon_cd;
	}
	public void setWthr_icon_cd(String wthr_icon_cd) {
		this.wthr_icon_cd = wthr_icon_cd;
	}
	public String getWthr_cl_nm() {
		return wthr_cl_nm;
	}
	public void setWthr_cl_nm(String wthr_cl_nm) {
		this.wthr_cl_nm = wthr_cl_nm;
	}
	public int getFn_dst_cnct() {
		return fn_dst_cnct;
	}
	public void setFn_dst_cnct(int fn_dst_cnct) {
		this.fn_dst_cnct = fn_dst_cnct;
	}
	public int getUtrfn_dst_cnct() {
		return utrfn_dst_cnct;
	}
	public void setUtrfn_dst_cnct(int utrfn_dst_cnct) {
		this.utrfn_dst_cnct = utrfn_dst_cnct;
	}
	
	
	
}