package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTbbsModlInf;

/**
 * TbbsModlInf - ValueObject Extended class for table [TBBS_MODL_INF].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 02. 16
 */
public class TbbsModlInf extends BaseTbbsModlInf {

	private String mapped_menu_nm;
	private String top_menu_nm;
	private String mid_menu_nm;
	private String bot_menu_nm;
	private String mapped_yn;
	private int tmpl_seq;
	private String sys_nm;
	private String url;
	
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	 
	public String getMapped_menu_nm() {
		return mapped_menu_nm;
	}
	public void setMapped_menu_nm(String mapped_menu_nm) {
		this.mapped_menu_nm = mapped_menu_nm;
	}
	public String getTop_menu_nm() {
		return top_menu_nm;
	}
	public void setTop_menu_nm(String top_menu_nm) {
		this.top_menu_nm = top_menu_nm;
	}
	public String getMid_menu_nm() {
		return mid_menu_nm;
	}
	public void setMid_menu_nm(String mid_menu_nm) {
		this.mid_menu_nm = mid_menu_nm;
	}
	public String getBot_menu_nm() {
		return bot_menu_nm;
	}
	public void setBot_menu_nm(String bot_menu_nm) {
		this.bot_menu_nm = bot_menu_nm;
	}
	public String getMapped_yn() {
		return mapped_yn;
	}
	public void setMapped_yn(String mapped_yn) {
		this.mapped_yn = mapped_yn;
	}
	public int getTmpl_seq() {
		return tmpl_seq;
	}
	public void setTmpl_seq(int tmpl_seq) {
		this.tmpl_seq = tmpl_seq;
	}
	public String getSys_nm() {
		return sys_nm;
	}
	public void setSys_nm(String sys_nm) {
		this.sys_nm = sys_nm;
	}


}