package kr.co.ta9.pandora3.pcommon.dto;

import kr.co.ta9.pandora3.pcommon.dto.base.BaseTsysPosInf;

/**
 * TsysPosInf - ValueObject Extended class for table [TSYS_POS_INF].
 *
 * <pre>
 *     Generated by CodeProcessor. Yon can freely modify this generated file.
 *     Copyright &amp;copy 2004 by Pionnet, Inc. All rights reserved.
 * </pre>
 *
 * @since 2019. 11. 05
 */
public class TsysPosInf extends BaseTsysPosInf {

}